### ISSUE TITLE
PHP modules do not load correctly for 5.6

### ISSUE THREAD

**Issue by smutek** [wplib/wplib-box#101]
On fresh install WP dashboard displays the following: Warning! PHPRedis module is unavailable, which is required by WP Redis object cache.

**Comment by mikeschinkel** [comment]
@smutek Well, crap.  

Thanks for checking out the box, and for the bug report.  

On Friday we released a new version of the box image, it may have an issue.  Let me see if I can reproduce.

**Comment by smutek** [comment]
Absolutely, my pleasure. Thanks for the good work and the quick response.

**Comment by mikeschinkel** [comment]
Can I invite you to our WPLib Slack too?  I have your email address...

**Comment by smutek** [comment]
Sure!

**Comment by mikeschinkel** [comment]
@smutek Short term before we issue a bug fix you can simply rename `var/www/content/object.cache.php` [as described here](https://github.com/wplib/wplib-box/blob/master/FAQ.md#why-is-wplib-box-caching-things).  This will disable the warning and disable the caching.

**Comment by mikeschinkel** [comment]
@clubdeuce:

I found two problems:

1. It seems that C-based PHPRedis extension is not available.  I could not figure out why as that is probably something in the image build process.

2. The `redis-server` fails to start, but by running `sudo chmod -R 777 /var/log/redis/redis-server.log` I was able to start it.  Of course with the issue in #1 above, this fix is moot.

**Comment by clubdeuce** [comment]
@mikeschinkel I am going to need you to walk me through this issue. The `redis` module is installed in the box and working with PHP 7.0. However, it is not working with PHP 5.6.

The `redis` server is starting correctly, so I do not understand what you are referring to in item 2 in your comment to me.

**Comment by mikeschinkel** [comment]
@clubdeuce my comments are less important. Do a clean install and the look at the admin console and see the error that is displayed.
