### ISSUE TITLE
XDEBUG not working for PHP 5.6 or 7.0 on `0.10.7.2`

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#107]
XDEBUG not working for PHP 5.6 or 7.0 on `0.10.7.2`

Evidently these files do not have the required directives:

- `/etc/php/5.6/fpm/conf.d/20-xdebug.ini`
- `/etc/php/7.0/fpm/conf.d/20-xdebug.ini`

It should have _(at least some of; not sure about the last)_:

    xdebug.remote_enable=1
    xdebug.remote_connect_back=1
    xdebug.remote_port=9000
    xdebug.remote_autostart=1
    xdebug.ide_key=PHPSTORM

For anyone who runs into this before it is fixed in the box you also need to run (one of these) after adding the above directives:

    sudo service php5.6-fpm restart
    sudo service php7.0-fpm restart

Note: I have tested this on 5.6 but not on 7.0 yet...

**Comment by clubdeuce** [comment]
@mikeschinkel Xdebug is currently working in `0.10.7.2` for both PHP 5.6. and 7.0. The files you mentioned above are actually symbolic links to `/etc/php/5.6/mods-available/xdebug.ini` and `/etc/php/7.0/mods-available/xdebug.ini`, both of which have the correct directives.

Xdebug does not work properly on PHP 5.6 on box version `0.10.7.1`. Are you sure you have updated to `0.10.7.2`?

**Comment by mikeschinkel** [comment]
@clubdeuce The reason I posted is that XDEBUG was not working for me until I made those changes...

The fact is was not working is the only reason I started to look into it.  Maybe I did something wrong?

**Comment by clubdeuce** [comment]
@mikeschinkel You must be, as Xdebug is properly configured and working for me in box version `0.10.7.2`.

**Comment by mikeschinkel** [comment]
@clubdeuce I will test again later this weekend on a new project and then see it I can reproduce the problem.

**Comment by mikeschinkel** [comment]
@clubdeuce BTW, this makes me thing we might want to document our configurations where users (including me) can find them and not make invalid assumptions.

**Comment by mikeschinkel** [comment]
So I tested it on a new setup and it worked fine.  Not sure what happened when I was working on this one, so sorry for the bother.
