### ISSUE TITLE
Document MailHog

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#108]
At what URL will be find the MailHog admin?  Anything else we need to know about it?

**Comment by mikeschinkel** [comment]
@clubdeuce Also, I guess we cannot set a fixed URL given that currently people may create multiple boxes.  So we probably need to discuss?

**Comment by clubdeuce** [comment]
Mailhog is available at `http://your.url:8025`

**Comment by mikeschinkel** [comment]
Where can I find that in configuration files in the box, so I can better understand it?  

And is there any reason we can't have it load via http://mailhog.wplib.box?  I say this assuming we need to fix `wplib.box` as the `hostname` and suggest people set their own domains using aliases.

**Comment by clubdeuce** [comment]
@mikeschinkel There is no configuration for Mailhog. That is where the program itself listens by default.

It can be configured using environment variables, but I saw no reason to alter the defaults. Information about configuration options can be found [here]{https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md)

**Comment by clubdeuce** [comment]
I have created an nginx reverse proxy for the mailhog installation.
