### ISSUE TITLE
Document Adminer

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#109]
Document Adminer - what URL will it be located at?  What else do we need to know?

**Comment by mikeschinkel** [comment]
@clubdeuce Also, I guess we cannot set a fixed URL given that currently people may create multiple boxes.  So we probably need to discuss?

**Comment by clubdeuce** [comment]
I think adminer should be set as a subdirectory of the box url, i.e. `http://your.url/adminer`.

**Comment by mikeschinkel** [comment]
@clubdeuce Not a fan of `http://your.url/adminer` because the box should be designed to allow people to blow away the provided `/www/` directory and replace with their own existing project.  If they do that then the will loose Adminer and I was instead thinking of Adminer as being a feature of the box, not a feature of a project.

And is there any reason we can't have it load via http://adminer.wplib.box?  I say this assuming we need to fix `wplib.box` as the `hostname` and suggest people set their own domains using aliases.

**Comment by clubdeuce** [comment]
@mikeschinkel Having the URL for adminer be a subdirectory of the box URL does not require the adminer script to be installed in a subdirectory of the `www` directory.
