### ISSUE TITLE
Add ZeroMQ to WPLib Box

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#112]
http://zeromq.org/bindings:php

**Comment by clubdeuce** [comment]
@mikeschinkel What are we going to do with ZeroMQ?

**Comment by mikeschinkel** [comment]
@clubdeuce ZeroMQ is a lightweight message queue.  It _may_ be redundant with Gearman, or it may actually be a good companion.  Unlike other message queues that run as servers it is a C library that requires a PHP extension.

Where it could be useful is to improve performance of things that can be queued.  For example, assume we upload an image but want to push to Amazon S3?  Our web page could instantaneously send a message to an uploader queue and return.  Then Gearman or even a simple cron task running a PHP script could pull the message from the uploader queue and then upload the file to Amazon S3.

Other use-cases could be sending transactional emails and rebuilding caches when a record is updated that should invalidate the cache.  

Maybe this is an Installable Package?  Or maybe since it is so small we just add to the box?
