### ISSUE TITLE
Install PHP mbstring extension

### ISSUE THREAD

**Issue by naomicbush** [wplib/wplib-box#122]
[mbstring](http://php.net/manual/en/mbstring.installation.php) is not a default PHP extension, but is used by some popular PHP libraries, so it must be explicitly enabled. Here's how I did it manually on the box, for PHP 7.0:

`sudo apt-get update`
`sudo apt-get install php7.0-mbstring --fix-missing`

But it would be nice to have this already done :-)

**Comment by mikeschinkel** [comment]
Funny.  I ran into this same issue yesterday.  :-)

@clubdeuce  Looks like something we need to add to next.

**Comment by clubdeuce** [comment]
This has been added to the build configuration and will be present in the next release of the box.
