### ISSUE TITLE
Add Laravel and Spark installers

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#123]

**Comment by clubdeuce** [comment]
This will also require `composer` to be installed.

**Comment by mikeschinkel** [comment]
@clubdeuce If there are closed source versions of Spark we have to be careful not to include them.

**Comment by clubdeuce** [comment]
@mikeschinkel The installer is open sourced on GitHub, so there is no issue with including it in the box.

**Comment by mikeschinkel** [comment]
@clubdeuce ok.  Just wanting to make sure we don't violate a license. :-)
