### ISSUE TITLE
Add a ~/.my.cnf file?

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#130]
I am about to teach a class on WordPress and it would be great to simplify them having to learn the user and password to get into `mysql`, at least initially.

So I am proposing we add the following as `/home/vagrant/.my.cnf`:

    [client]
    user=wordpress
    password=wordpress

Given this is a local dev box I don't see a security concern.  What do you think?

**Comment by clubdeuce** [comment]
This can easily be added. Or you could just `mysql -u root`.

**Comment by mikeschinkel** [comment]
@clubdeuce Or maybe this?

    [client]
    user=root
    password=
