### ISSUE TITLE
Install MariaDB as an option to MySQL

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#136]
@clubdeuce This ticket is here so we can discuss next time we are reviewing potential tickets. 

Also, if anyone is looking at this and has a strong desire to see us add MariaDB please let us know in the comments and also let us know why you need this instead of MySQL.  Thanks!

**Comment by clubdeuce** [comment]
@mikeschinkel I think we should just choose either MySQL or MariaDB and install only that one. Having both adds to the size of the box and sets a precedent of options that may lead to substantial box bloat _(e.g. Redis and Memcached, Apache and Nginx, APC and Opcache, etc)_.

**Comment by mikeschinkel** [comment]
@clubdeuce Okay, so we have a pro-con scenario here.

**Add Every Solution Per Component:**
Cons:
- Increasing complexity and chance of conflicts between installed items.
- "Bloat"
- Additional need for docs
- _(Anything else?)_

**Add Only One Solution Per Component:**
Cons:
- Some people will want to mirror their deployment so won't use our box. 
- Some people will just want to use the one we did not pick so they won't use our box. 
- For those who won't use our box they will probably build their own, or use a competitor. If they build their own they may decide to release their as yet another competitor.
- _(Anything else?)_

 As our goal for WPLib Box is to become ubiquitous, the cons of adding only one are contrary to our goals. But the cons of adding many are also a concern.

So, can we possibly consider a 3rd option?  

Many things keep pointing back to a need for _**"Installable Packages"** (#118)_.  So I am going to propose the following as a strawman for discussion:

1. We pick one solution to be installed in the box _(Maybe: Nginx, MariaDB and Redis as they are all the more leading edge of each option?)_

2. We create _Installable Packages_ for the other options.  In some cases the Installable Packages might need to uninstall its alternatives, e.g maybe MySQL and MariaDB can't co-exist? In which case we'd need uninstallers for each and also an Installable Package for the default option. But we should strive to support side-by-side install, if possible.

3. We implement out API/Console/CLI to recognize that we might have more than one installed.

4. We have an official list of Installable Packages, maybe in a `packages.json`file in the repo?  

5. We should create our own repo for Installable Packages where a package is a `.ZIP` file format maybe with a `.package` extension containing all the files that are needed to install the package and we can tie the packages to the O/S version we are running on.  

So I would not want to depend on the user running `apt-get` as it is very fragile and can frequently result in hard to debug issues.  To create these we'd use apt-get to install to our build system, test to make sure it works, then collect up the files that have been added into a `.package` file and also write scripts to change the files that need to be changed. This way the only thing that could really fail would be if the download failed because we'd know that our Installable Package would work on our particular box.

Once we have a package created for an O/S we theoretically would never have to recreate the package, at least until we upgrade to a newer base O/S. 

Thoughts?

**Comment by clubdeuce** [comment]
@mikeschinkel My initial thoughts are of the Microsoft vs Apple debate. Apple provides one solution that **_just works_**. Microsoft opens the system to allow for all different types of video cards, sound cards, network cards, etc. and half your day is spent trying to troubleshoot some non-standard combination that has conflicting drivers.

My hesitation with the packages proposal is that we will now have to maintain not only the box, but also an individual package for each piece of software that someone _might_ want to install, as well as the installer mechanism itself.

That being said, I understand your point regarding ubiquity. That being said, the library upon which this box is named is itself _**highly**_ opinionated.

Regardless of which approach we take, we will still be deciding what software is supported, e.g. we are either installing MariaDB and MySQL in the box or we are installing MariaDB and providing and installation package for MySQL.

If we are striving for ubiquity, at some point a decision will have to be made regarding what software we are supporting. The decision will be either:
+ What software are we installing in the box?
+ What installable packages are we going to maintain?

We are still determining the available 'packages'.

At that point, i believe it is simpler to tell people that will simply have to accept a longer initial download experience (contrary to my original post on this issue, and much like the higher investment in Apple hardware), and pre-install all software.

**Comment by mikeschinkel** [comment]
@clubdeuce 

> My initial thoughts are of the Microsoft vs Apple debate. 

I like your analogy, but I take it in a different direction: Apple provides the core iPhone and a small set of Apps that it chooses to support directly. Then Apple empowers others to extend the iPhone with Apps.   

As you know it was not unlike Apple enabled Apps that the iPhone really took off in the market.

> _now have to maintain not only the box, but also an individual package for each piece of software that someone might want to install_

Quite the contrary. 

The package mechanism would allow us to _**limit the things that we need to support outselves**_ and instead empower others to build and maintain the more esoteric ones.

This approach would keep us from having to decide between saying a black and white yes or no when it comes to someone asking to have something added to the box.  We might answer _"If you build a package we'll include it as a standard option if you make it easy for us to maintain."  Or we might have to say _"Build a package for that. We don't see enough demand for us to maintain that."_  

But at least we don't have to tell them an inflexible _"no."_

> as well as the installer mechanism itself.

I have envisioned this installer mechanism to be very light weight. A package could be ZIP file that can be downloaded containing required files, a `manifest.json` that says where to put the files and a PHP script that would make any needed changes to config files.  

And then our installer would be a simple PHP script that would read a `packages.json` file for the box that would list the desired packages and provide any necessary arguments for each package.  One the spectrum of the find of things we've done this far, the installer would be pretty trivial.

And over time we could improve the installer script and the template for a package script to make it easier for people to create new packages. And we could solicit those improvements from users who end up building packages for themselves and want to distribute them.

**Comment by clubdeuce** [comment]
@mikeschinkel Your argument is reasonable.

**Comment by clubdeuce** [comment]
This has been implemented as a docker container in 0.14.0.
