### ISSUE TITLE
Install the PHP XMLWriter extension

### ISSUE THREAD

**Issue by naomicbush** [wplib/wplib-box#140]
I needed this for the Braintree PHP library, and manually installed with

`sudo apt-get install php7.0-xml`

**Comment by mikeschinkel** [comment]
Seems like we should add this, no @clubdeuce?

@naomicbush BTW, we have a ticket just before yours (#139) where we are exploring how to empower the user of the box to add extensions.  We want it to be part of the box configuration so if you commit to a repo and someone else checks out from the repo their box will install the extension too on `vagrant up`, and we want to do it in an manner that is not likely to break, unlike VVV's provisioning.

**Comment by mikeschinkel** [comment]
@naomicbush - BTW, I am just curious, what functions or classes were missing that Braintree PHP library required?

**Comment by clubdeuce** [comment]
@naomicbush @mikeschinkel I am surprised by this issue, as the PHP XMLWriter extension is already included in the box as of (0.10.7.3)[76414ad8f1d6c74bdfd79d61f283125c2ae127b0].

**Comment by naomicbush** [comment]
@clubdeuce I don't have any update notifications and I'm pretty sure I'm on 0.10.7.3, but I'll take your word if you say it's in 0.10.8 :-)

**Comment by clubdeuce** [comment]
@naomibush Very good.

**Comment by naomicbush** [comment]
I can confirm that this was *not* working in 0.10.8. Note that I had to install the php 7.0 version of the module. @clubdeuce Perhaps you only installed it for one of the earlier PHP versions?
