### ISSUE TITLE
Updating domain name doesn't update Mailhog and Adminer

### ISSUE THREAD

**Issue by nonameolsson** [wplib/wplib-box#143]
I have tried multiple times to update my domain name, but it doesn't update the domain name for Mailhog / Adminer. 

To get more info I did SSH into the box to look in the Nginx config files. It still shows `mailhog.wplib.box` and `adminer.wplib.box`  in the site configuration.

`/etc/nginx/sites-enabled/mailhog.conf`
```
server{
        listen 80;
        server_name mailhog.wplib.box;

        location / {
                proxy_pass http://localhost:8025;
        }
}
```

`/etc/nginx/sites-enabled/adminer.conf`
```
server {
    listen 80;
    server_name adminer.wplib.box;
    root /srv/sites/adminer;

    index index.php;

    # Pass all .php files onto a php-fpm/php-fcgi server.
    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
                return 404;
        }
        # This is a robust solution for path info security issue and works with "cgi.fix_pathinfo = 1" in /etc/php.ini (default)

        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
    }
}
```

This is the `Vagrantfile`
```
Vagrant.configure(2) do |config|

    File.write('IP', "10.10.10.#{rand(10..250)}") if not File.exists?('IP')

    config.vm.box = "wplib/wplib"
    config.vm.hostname = "srf.box"
    config.hostsupdater.aliases = [
        "adminer.srf.box",
        "mailhog.srf.box"
    ]

    config.vm.network 'private_network', ip: IO.read('IP').strip

    config.vm.synced_folder "www", "/var/www"

    config.ssh.forward_agent = true
    config.ssh.insert_key = false

    config.vm.provision "shell", path: "scripts/provision.sh"

    config.trigger.before :halt do
        run_remote "mkdir -p /vagrant/sql && mysqldump -u wordpress -pwordpress wordpress > /vagrant/sql/current.sql"
    end

end
```

Am I missing something? The web site is accessible with my new domain name. If I manually change to the new domain name i the *.conf-files and restart the Nginx service it will work.

**Comment by fgilio** [comment]
Interesting... I also use a custom domain and both `mailhog` and `adminer` don't work. Maybe is the same situation, I didn't check the *.conf-files

**Comment by mikeschinkel** [comment]
@nonameolsson I am aware of the situation but I am not 100% sure I understand your question.  The nginx `.conf` files you posted do not have your new domain names: `"mailhog.srf.box"` and `"adminer.srf.box"`  

Can you clarify the issue?

**Comment by nonameolsson** [comment]
The instructions says:
In other words, change this:

	config.vm.hostname = "wplib.box"

To _(something like)_ this:

	config.vm.hostname = "dev.example.com"

Save the changes to `Vagantfile` and then run the following commands to reload the Vagrant configuration, and then open in your browser. _(Be sure you replaced the domain name in the 2nd command with your own local domain name)

---

When we do that and reload the box the main domain name is updated. I did change `wplib.box´ in Vagrantfile to `srf.box` at all places as you can see in my previously posted Vagrantfile. After running `vagrant reload` I can navigate to `srf.box` to access the website. But the values in the config files are the same as before `adminer.wplib.box` and `mailhog.wplib.box`. They haven't changed. 

Do I explain me? :)

**Comment by mikeschinkel** [comment]
@nonameolsson @fgilio BTW, the current architecture of the box is what we could do to make it work it for the easiest "out of the box" experience (pun intended. :-)  But we are working on a new architecture that will support multiple sites that will have an admin console and an API to allow you to add and reconfigure sites.  Once we get to that then wplib.box will be the admin console and you would set up your domains how ever you want them to work.

That said, I am trying to understand why you might want to change the domain names of        "adminer.wplib.box" and "mailhog.wplib.box" to something else?  We want how you want to use the box, we just have to understand your workflow better.

**Comment by mikeschinkel** [comment]
@nonameolsson Ah yes.  There is nothing in the box that would chance the NGINX config files, and those instructions were written before we had Adminer or Mailhog so we were not thinking that there was anything to change. And it did not occur to us to update the instructions that you quoted when we added Adminer or Mailhog.

That said, we are going to release a pretty big improvement soon so I don't know if we want to optimize for this older architecture in the short term.  With the new box we hope to enable these kind of changes via admin console and CLI so you don't have to edit files.  Does that sound like an improvement and if not what would you expect differently?

**Comment by nonameolsson** [comment]
Thanks for the explanation @mikeschinkel!

I think it is for the same reason I don't want to use `wplib.box`. The Readme says:
```
To use WPLib Box for a local domain name other than wplib.box edit the Vagrantfile and replace the text "wplib.box" with your preferred local domain name (we recommend "dev.your-production-domain.tld"):
````

It's confusing to have dev.mysite.com when developing, but having to use `mailhog.wplib.box` and `adminer.wplib.box`.

**Comment by mikeschinkel** [comment]
> _It's confusing to have dev.mysite.com when developing, but having to use mailhog.wplib.box and adminer.wplib.box._

Hmm.  Assuming we had an admin console, where would you expect that to be?   Note that we plan to enable as many sites in development on one install as you want.

**Comment by nonameolsson** [comment]
Would there be different adminer's and mailhog's for different sites?

**Comment by fgilio** [comment]
Hi!
@mikeschinkel all that sounds amazing. I think it's ok to have the admin console in wplib.box and a domain for each site.
In the meantime... we'll just have to update the *.conf-files manually. Not that bad.

**Comment by clubdeuce** [comment]
There is an easy fix that will allow the adminer and mailhog sites to respond to whatever domain name is set in the Vagrantfile.

@nonameolsson @fgilio Before we make this change in the next release, you can simply change the server names in `/etc/nginx/sites-enabled/adminer.conf` and `/etc/nginx/sites-enabled/mailhog.conf` to `server_name adminer.*` and `server_name mailhog.*` respectively.

**Comment by fgilio** [comment]
@clubdeuce nice, thanks!

**Comment by mikeschinkel** [comment]
@nonameolsson 
> Would there be different adminer's and mailhog's for different sites?

Dunno.  Should there be?

**Comment by nonameolsson** [comment]
I don't know :) I think that it depends on the use case. For simplicity, maybe there should be just one that manages all sites?

**Comment by mikeschinkel** [comment]
> _maybe there should be just one that manages all sites?_

That was what we have been thinking because it did not occur to us otherwise.  

That said, given the change @clubdeuce mentioned you should be able to access them via subdomain of any domain on the box, so maybe that is the best of both worlds?

**Comment by nonameolsson** [comment]
That I like! Sounds like a very good plan. Keep up the good work, I really like the box so far!

**Comment by fgilio** [comment]
Thanks guys!!

Also... @clubdeuce suggestion worked flawlessly :D

**Comment by mikeschinkel** [comment]
@nonameolsson @fgilio 

Thanks.  

> _all that sounds amazing._
> _I really like the box so far!_

And it is super motivating for us to hear that.

**Comment by clubdeuce** [comment]
@fgilio Very good.
