### ISSUE TITLE
32-bit image Box

### ISSUE THREAD

**Issue by gurudevendranath** [wplib/wplib-box#144]
There should be a 32-bit image box as like 64-bit image box. 
Currently I have trouble to run 64-bit image box at my end as my PC (Bios) doesn't supports hardware virtualization.
I think 32 bit-bit image box will run without any troubles at my end.

**Comment by clubdeuce** [comment]
@mikeschinkel Your thoughts on this?

**Comment by mikeschinkel** [comment]
@clubdeuce I think if we are going to tackle this it would only be after we get to version `1.0`, and then we'd need to see how many people really need it.  I am included to say _"Maybe some day, but not until we know if there are many people who need it."_  So for now, I'm closing and we can revisit in the future if need be.
