### ISSUE TITLE
Update Ruby and Gem

### ISSUE THREAD

**Issue by dsgnr** [wplib/wplib-box#148]
I was attempting to install Wordmove on WPlib-box, unfortunately, this is not possible without updating Gem. I manually updated Ruby in order to install Gem, but Wordmove is on a newer version.

The versions currently installed on this box are quite a bit lower than that on VVV as I was unable to update Gem for some reason, I thought I'd ask here!

**Comment by nonameolsson** [comment]
I have never heard of Wordmove before, but it sounds really great! I think it would be nice to get it to work with Wplib-box. I will try to get it to work.

**Comment by nonameolsson** [comment]
Nope, can't install it.

**Comment by dsgnr** [comment]
I did actually manage to get it installed. 
`gem install rubygems-update
update_rubygems
gem update --system`

Gem went from 1.8 to **2.6**

Haven't tested Wordmove fully yet but it didn't cry when I tried to install it.

**Comment by nonameolsson** [comment]
@dsgnr Did you do that on provision or did you ssh into the box?

**Comment by dsgnr** [comment]
@nonameolsson I don't know how to do this at the provision stage so was via ssh'ing into the box.

I did have to update ruby itself to a newer version prior to updating gem.

**Comment by mikeschinkel** [comment]
@dsgnr @nonameolsson FYI, watching your discussion here closely...

**Comment by dsgnr** [comment]
@mikeschinkel where in the code is the Ruby and Gem versions provided? I'd like to see if I can work out how to check the Ruby and Gem versions, update them if necessary and install Wordmove on provision.

**Comment by mikeschinkel** [comment]
@dsgnr As far as I know, nowhere. We do not install anything Ruby or Gem into WPLib Box. Whatever is in the box comes from [Ubuntu `14.04 LTS`](http://packages.ubuntu.com/trusty/ruby).

**Comment by nonameolsson** [comment]
@dsgnr You could try to upgrade Ruby and Gem in the provision-script! Let me know how it goes.

**Comment by mojenmojen** [comment]
I have wordmove working with Wplib-box. I didn't modify the provision script (not sure how to do that) but I did have to install ruby 2.3.1 on the vagrant box first.

**Comment by dsgnr** [comment]
@mojenmojen that's correct, you'll need to install rubygems if it's not already installed

**Comment by mikeschinkel** [comment]
We will be implementing Wordmove as an "Installable" which basically means a Docker Container. See #416.
