### ISSUE TITLE
Make project compatible with composer create-project

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#15]

**Comment by clubdeuce** [comment]
Further reading indicates this is only possible by submitting to [Packagist](http://packagist.org). @mikeschinkel Shall we do that?

**Comment by mikeschinkel** [comment]
@clubdeuce Are there any downsides to submitting to Packagist?

**Comment by clubdeuce** [comment]
@mikeschinkel Not really. It would make it easier for users to adopt.

**Comment by mikeschinkel** [comment]
Then we should do it.

**Comment by mikeschinkel** [comment]
@clubdeuce I see you assigned to me.  What do I need to do for this?

**Comment by clubdeuce** [comment]
@mikeschinkel Simply [submit](https://packagist.org/packages/submit) the repo to Packagist.

**Comment by mikeschinkel** [comment]
@clubdeuce Is this all we need?

https://packagist.org/packages/wplib/wplib-box

**Comment by mikeschinkel** [comment]
It says _"(Not Auto-Updated)"_.  I added the web hook on GitHub, so not sure what else I need to do to fix.

**Comment by clubdeuce** [comment]
@mikeschinkel This is currently working as expected.

**Comment by mikeschinkel** [comment]
See #504 - Reimplement Composer as a (PHP) ScriptComponent.
