### ISSUE TITLE
When you ssh you should land in site root

### ISSUE THREAD

**Issue by andreasnrb** [wplib/wplib-box#16]
When you ssh into vagrant I think that the directory you land in should be the default synced folder, site root. Currently you end up in the home directory. When directory matters thats where I usually want to go.

**Comment by mikeschinkel** [comment]
Hey @andreasnrb - @clubdeuce and I are discussing this and wondering why this is needed since you have access to the web root on the host machine.   

Is there a good use-case for this we are not thinking about?

**Comment by andreasnrb** [comment]
Cant run wp cli from host computer for example. At least not out of the box.

**Comment by mikeschinkel** [comment]
@andreas Gotcha, thanks.
