### ISSUE TITLE
Can't access localtunnel

### ISSUE THREAD

**Issue by nonameolsson** [wplib/wplib-box#161]
Steps to reproduce:
1. `vagrant ssh`
2. `lt --port 80` 
3. Copy the generated link.
4. Visit the link from a browser. 

Result: 
A blank page with the text `no active client for 'ezpeeeyejd'`. I have tried this multiple times without success. Am I missing something?

**Comment by clubdeuce** [comment]
@nonameolsson No, you are doing it correctly. And it is working for me.

**Comment by mikeschinkel** [comment]
@nonameolsson Which version of the box are you using?

**Comment by mikeschinkel** [comment]
@nonameolsson I just tested your listed steps and it worked for me on `0.10.9`.

**Comment by mikeschinkel** [comment]
@nonameolsson Have you looked at any of these?

- https://github.com/localtunnel/localtunnel/issues/60
- https://github.com/localtunnel/server/issues/21
- https://github.com/localtunnel/localtunnel/issues/53

**Comment by fgilio** [comment]
It is working ok for me, too.

**Comment by nonameolsson** [comment]
@mikeschinkel Yeah, but it doesn't work. I'll try on a new box/project to see if it helps.

**Comment by adrianfime27** [comment]
yeah, but.. how to made for running in your pc @fgilio?

**Comment by fgilio** [comment]
Hi @adrianfime27 
I'm sorry to tell you that this isn't working any more for me. Not from inside the box.

But, I managed to use it from the hosts. Simply [install localtunnel](https://github.com/localtunnel/localtunnel) with: `yarn global add localtunnel` or, if you use npm, `npm install -g localtunnel`
And run it like this: `lt -p 80 -l sitedomain.dev` or, if you are using https, `lt -p 443 -l sitedomain.dev` 

Hope it helps!

**Comment by clubdeuce** [comment]
I am unable to replicate this issue. `lt -p 80` from inside the virtual machine produces a  working URL for me.
