### ISSUE TITLE
Remove soon-to-be optional items

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#163]
HHVM
ZeroMQ
Gearman

**Comment by fgilio** [comment]
I'm in favor of removing HHVM.
IMO it it's no longer necessary since we have PHP7 around.

**Comment by mikeschinkel** [comment]
@fgilio Thanks for the comment.  

To be clear the reason we are doing this is in preparation for a new release strategy where we are going to have named and numbered releases _(similar to how Apple names and numbers Mac OS X)_ and for each named release we define the supported software and versions that we include.

In addition we will create "Installable packages" that will allow you to add to or upgrade the software for a given release.  

After reviewing the software we should include we realized that HHVM, ZeroMQ and Gearman would be better as installable packages, at least for now.

**Comment by mikeschinkel** [comment]
BTW, there are a lot of create reasons for using the HHVM over PHP7 _(the Hack language has many really useful features that PHP7 does not)_, but since most people do not currently use Hack with WordPress we decided that it should not be our primary process VM.

**Comment by fgilio** [comment]
Hey @mikeschinkel, thanks for taking the time to explain all this. I really like how this is evolving and the direction you guys are going.

**Comment by mikeschinkel** [comment]
@fgilio Thanks.  If you have any suggestions, please let us know by posting them as new issues here on GitHub.

**Comment by fgilio** [comment]
Sure!
