### ISSUE TITLE
OpenSSL certificate verify failed

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#167]
The following failed when attempting to access a URL via `file_get_contents()`:

```
 Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /var/www/content/mu-plugins/wabe.org/modules/component-gaussholder/component-gaussholder.php on line 78
```

This seems to imply it can be solved by fixes to the box:
- http://stackoverflow.com/a/32366242/102699

Also:
- http://php.net/manual/en/migration56.openssl.php

**Comment by clubdeuce** [comment]
@mikeschinkel Is this still an issue?

**Comment by mikeschinkel** [comment]
@clubdeuce Have not seen in a while so closing.  Will reopen or add a new ticket it if recurs.
