### ISSUE TITLE
add default salt constants to wp-config

### ISSUE THREAD

**Issue by andreasnrb** [wplib/wplib-box#17]
Some plugins uses the the salt constants. Consider adding them with default empty value in wp-config unless salt.php is found.

**Comment by clubdeuce** [comment]
I think we could just add salt values to the `wp-config.php` so that they are defined when needed. I do not think we need to be concerned with unique values as this is a local development environment.

**Comment by mikeschinkel** [comment]
@clubdeuce Exactly.  We just need the constants to exist so that code that expects them does not crash.
