### ISSUE TITLE
Error message after vagrant up

### ISSUE THREAD

**Issue by mojenmojen** [wplib/wplib-box#170]
Vagrant 1.8.7
OS X 10.11.6

Ran:
git clone https://github.com/wplib/wplib-box.git
cd wplib-box
vagrant up

Then got this:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'wplib/wplib/' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'wplib/wplib/' (v0) for provider: virtualbox
    default: Downloading: wplib/wplib/
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

**Comment by mikeschinkel** [comment]
@mojenmojen Thanks for trying out WPLib Box.

Sounds like Vagrant just had a connectivity issue downloading the Linux image.

Run `vagrant destroy` and then `vagrant up` again to see if that fixes it.  And be sure you have good connectivity when you run the `vagrant up`. 

Let me know if this fixes it for you, or if you need any other help.

**Comment by mojenmojen** [comment]
Thank you for the prompt reply. I tried it in on another computer and it worked fine so there's something happening on my end which I'll need to troubleshoot. Sorry about that!

**Comment by mikeschinkel** [comment]
@mojenmojen No worries at all.  Please let us know if we can help you with anything related to WPLib Box.

**Comment by mojenmojen** [comment]
In case anyone else comes across this, here was the problem:

http://stackoverflow.com/questions/40473943/vagrant-box-could-not-be-found-or-could-not-be-accessed-in-the-remote-catalog

Removing the embedded curl fixed it.

**Comment by mikeschinkel** [comment]
@mojenmojen Thanks for finding the issue and posting a link.

Yes, we are finding that Vagrant is causing us pain, such as [with 1.8.6](https://github.com/mitchellh/vagrant/issues/7964).
