### ISSUE TITLE
File permissions issue when updating Twenty Sixteen theme on fresh install.

### ISSUE THREAD

**Issue by oxygensmith** [wplib/wplib-box#172]
![wplib-box-file-permissions-issue-fresh-install-click-to-update-2016](https://cloud.githubusercontent.com/assets/51263/21159591/725116bc-c147-11e6-8285-e228d3b322ab.png)

**Comment by mikeschinkel** [comment]
I believe this is a duplicate of #266, which I have updated recently _(which is why I am closing this one and not that one.)_
