### ISSUE TITLE
cURL error 56: Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by baselbers** [wplib/wplib-box#173]
I think it has something to do with plugins like below that request files from outside from like cloud storage services (Amazon S3).
- [WooCommerce Helper](https://docs.woocommerce.com/document/woocommerce-helper/)
- WPML

I'm using Bitdefender and was thinking it has something to do with the firewall configuration, but there are no messages/warnings etc.

**Comment by mikeschinkel** [comment]
Hi @baselbers - Sorry for that slow reply.

Can you give more details about the error?  What were you doing?  Where did the error occur?

**Comment by baselbers** [comment]
Hi @mikeschinkel,

No worries, I've edited comment above. :)

**Comment by mikeschinkel** [comment]
@baselbers So you are seeing this as an error in your browser when you run a web page that uses one of these plugins?  If yes, is the error repeatable?  If yes to that, is there any chance we could get a copy of the site to test with on our end?

**Comment by baselbers** [comment]
Using Query Monitor plugin to watch errors and `wp_safe_remote_post` to request a remote url.

**Comment by baselbers** [comment]
Any news?

**Comment by mikeschinkel** [comment]
@baselbers Sorry, this slipped under the radar.  We've had an urgent client project the past month and things have been a bit crazy.  I'll try to find time to recreate this soon.

**Comment by baselbers** [comment]
Any news? :(

**Comment by clubdeuce** [comment]
@baselbers Can you provide a code sample that causes the error so that I can replicate and troubleshoot this issue?

**Comment by baselbers** [comment]
It happens when I for example import WooCommerce dummy data attachments.

![image](https://cloud.githubusercontent.com/assets/10761673/24666607/1bba533c-1961-11e7-8b25-9605794bc45f.png)

**Comment by baselbers** [comment]
I've even updated curl to latest version with no luck.

I use Query Monitor plugin to see the HTTP errors.

![image](https://cloud.githubusercontent.com/assets/10761673/24666832/b52ee668-1961-11e7-8621-541c0ebfa308.png)

**Comment by clubdeuce** [comment]
@baselbers Can you provide the file that you are using for the import?

**Comment by baselbers** [comment]
https://plugins.svn.wordpress.org/woocommerce/tags/2.6.4/dummy-data/dummy-data.xml?dl=1

**Comment by clubdeuce** [comment]
@baselbers Unfortunately, I am unable to replicate this issue. I was able to import the file you provided with no cURL errors. _**(However, there are numerous deprecated notices generated by the WordPress Importer plugin.)**_

My setup is:

+ Fresh WPLib Box v 0.11.0
+ WordPress 4.7.3
+ WooCommerce 3.0.0
+ WordPress Importer 0.6.3


<img width="1253" alt="screen shot 2017-04-04 at 1 09 57 pm" src="https://cloud.githubusercontent.com/assets/2600497/24669379/35834090-1938-11e7-86d3-5a01f201317c.png">
<img width="1266" alt="screen shot 2017-04-04 at 1 10 17 pm" src="https://cloud.githubusercontent.com/assets/2600497/24669378/35667aa0-1938-11e7-8ca8-088988266a6e.png">
<img width="1278" alt="screen shot 2017-04-04 at 1 10 32 pm" src="https://cloud.githubusercontent.com/assets/2600497/24669377/3565f440-1938-11e7-8793-7ed8267dba9a.png">

**Comment by clubdeuce** [comment]
@baselbers 
<img width="1264" alt="screen shot 2017-04-04 at 1 18 45 pm" src="https://cloud.githubusercontent.com/assets/2600497/24669665/495d3f52-1939-11e7-927a-4459745d7c71.png">

**Comment by baselbers** [comment]
Wow this is getting very strange. Do you have any idea what it could be? :(

**Comment by clubdeuce** [comment]
@baselbers Very good. The team apologizes for the delay in responding to this ticket.

**Comment by baselbers** [comment]
@clubdeuce Thanks for your help today and keep up the great work!
