### ISSUE TITLE
Potentially misleading message "If you are seeing this page, for some reason Vagrant has failed...

### ISSUE THREAD

**Issue by Shelob9** [wplib/wplib-box#182]
Sometimes I see this message
`If you are seeing this page, for some reason Vagrant has failed to mount your working directory into the website root. Please perform a vagrant reload to see if this resolves the problem.`

This makes me worry I have a problem, but everytime it is beacuse vagrant up is not done.

I suggest:

`If you are seeing this page, for some reason Vagrant is not done loading, or has failed to mount your working directory into the website root. Please make sure vagrant up is complete and if so, perform a vagrant reload to see if that resolves the problem.`

**Comment by mikeschinkel** [comment]
@clubdeuce Is this a message you generate, or one that Vagrant generates?

**Comment by clubdeuce** [comment]
@mikeschinkel This is a message I have generated. It can be modified to say whatever we like.

Ideally, I would also like to get @sarutole involved to make it far more appealing visually.

**Comment by clubdeuce** [comment]
@mikeschinkel Unless you say otherwise, I will use @Shelob9's suggested text.

**Comment by mikeschinkel** [comment]
@clubdeuce Go for it.
