### ISSUE TITLE
Add a changelog to the box for new releases of the box image.

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#19]
I guess this would be in the packer image but its location referenced in this repo's readme?

**Comment by clubdeuce** [comment]
@mikeschinkel We can do that.

**Comment by clubdeuce** [comment]
@mikeschinkel Were you thinking the changelog would be a file in the box itself, or present on Atlas?

**Comment by mikeschinkel** [comment]
@clubdeuce What are the best options?

**Comment by clubdeuce** [comment]
@mikeschinkel Atlas has the ability to list changes per release, but it is very disjointed in presentation.

A file in the box is possible, but my initial reaction is to just add it to the README here.

**Comment by mikeschinkel** [comment]
So adding the list in the private repo for the Box image seems appropriate since the changelist would be about the Box Image, not about `github.com/wplib/wplib-box`.  

However, people using  `github.com/wplib/wplib-box` would ideally want to see it and yet they do not have access to the private repo. Thus it seems that we should make it available in  `github.com/wplib/wplib-box`, but how to do so without duplication and the obvious potential inconsistency between the two if we forget to update one of them?

How about we look at creating a simple PHP page as a web service that captures a webhook we can configure on BitBucket to send notification of a push to WPLib Box Packer and that PHP page could do a pull on both the Bitbucket Packer repo and the GitHub box repo , copy the latest changelist from the packer repo to the GitHub box repo, commit and then push.  Will that work?

As for where to host that, we could maybe use PagodaBox, Google App Engine, or Rackspace's Carmina (all of which I think we can get for free.)  Or we could add to our Digital Ocean box.

Thoughts?

**Comment by clubdeuce** [comment]
@mikeschinkel That sounds reasonable.
