### ISSUE TITLE
Ensure CLI is at a specific revision when building the box

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#194]
Include a specific git tag

**Comment by mikeschinkel** [comment]
@clubdeuce Do you mind elaborating on exactly what you were thinking here?   It is possible that @MickMakes has already handled this in the work he has done, but I did not want to close this ticket without first understanding it.

**Comment by clubdeuce** [comment]
@mikeschinkel I believe the intent was to install the box CLI during the Packer build and lock that version of the CLI to that version of the box. It was a number of months ago, however, and I cannot currently recall the exact impetus for this.

**Comment by MickMakes** [comment]
This might be a little tricky in the way the BOX scripts are currently fetched. I'm going to punt this one on to 0.17 as it needs some thought put into it.

**Comment by mikeschinkel** [comment]
@MickMakes can't you just check out the correct version after cloning?
