### ISSUE TITLE
Enable stack configuration via vagrant up in box.json

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#201]
Enable stack configuration for a project (web server, DB server) by reading `box.json` on up and setting the appropriate configuration.  This will allow developers to commit that to a Git repo and then have their team members clone and a `vagrant up` will load and run the desired stack.

**Comment by khromov** [comment]
Throwing an example `box.json` structure out there, inspired by VVV and general Vagrant use:

```json
{
  "name": "My awesome site",
  "domains": [
    [
      "example.com"
    ],
    [
      "www.example.com"
    ]
  ],
  "database": "setup/init-db.sql",
  "composer": true,
  "ssl": false,
  "postprocess_hooks": [
    {
      "command": "wp core install",
      "sudo": false,
      "run_inside_box": true
    },
    {
      "command": "dictator impose setup/dictator.yml",
      "sudo": false,
      "run_inside_box": true
    },
    {
      "command": "cp setup/advanced-cache.php public/wp/advanced-cache.php",
      "sudo": false,
      "run_inside_box": true
    },
    {
      "command": "\"define('WP_POST_REVISIONS', 100);\" >> wp-config.php",
      "sudo": false,
      "run_inside_box": true
    },
  ]
}
```

Some clarifications:

* `database` would import an SQL database file.
* SSL would automatically configure WP with `FORCE_SSL_ADMIN` = true. Self-signed cert would be enough.
* The postprocess commands are very important and I've added a few use cases for them.

Let me know what you think @mikeschinkel

**Comment by khromov** [comment]
Also, check out Dictator if you haven't, I feel it can be very powerful for initial setup without relying on a database dump.

https://github.com/danielbachhuber/dictator

**Comment by mikeschinkel** [comment]
@khromov Thanks. I am going to review this and come back with some thoughts and questions, hopefully later tonight.

**Comment by mikeschinkel** [comment]
Hi @khromov - Thank you for putting so much effort into this.  I have spent a couple hours now considering it and wanted to ask some questions make sure I understand: 

#### What were you primarily trying to showcase?

1. The naming, e.g. `database, composer, ssl, postprocess_hooks` etc.,
1. The syntax of how values would be assigned, e.g. `sudo: false`, `run_inside_box: true`,
1. The specific functionality, such as the `database` import and the `postprocess` commands, 
1. The implied overall scope of the configurability, 
1. All the the above, and/or 
1. Something else?

#### `postprocess_hooks`

When will they run?  First `vagrant up` and then `vagrant reload --provision`?

#### Some thoughts:

1. We definitely plan to implement extensibility in some form, and we are likely to implement using the easiest way possible at first but later we may implement some different approaches if we can identify easier to implement and/or more elegant solution.  How that might play out is commands initially but then later we may deprecate commands _(at least in docs)_ and recommend extensibility via containers.

2. We want to make the common cases as easy as we can, and the edge cases possible.  Your example `postprocess_hook`s are mostly common cases so we would like to make them much easier, e.g. maybe `install: true`, `core: 4.7.*`, `cache: advanced-cache`,  `config-defines: [ "WP_POST_REVISIONS:100" ]`, etc.  Of course for things that are edge cases, there needs to be the ability for the user to do whatever they need.

3. My gut is telling me that _(just)_ specifying a SQL to load will be too limiting.  We want to ensure that:
    - the box is completely transitory so the user can blow it away at any time and start over,
    - the database can be pushed to staging prior to launch and pulled from production after launch
    - and yet anything can be overridden by the developer if and when needed. 

    But I can't know for sure until we implement some more advanced proofs-of-concept.

4. Agreed on SSL.

5. Dictator looks interesting, although I do not like its name very much.  Many a truth said in jest?   

   Ignoring the name, it is not yet documented well enough for me to understand its full scope so it is hard to understand its full potential value. However, my lack of understanding it is moot because it requires WP CLI

    **One of our main product attributes is ensure reliability as much as possible** and while WP CLI is a great tool, in our experience it is too fragile for us to be comfortable making the box fundamentally dependent on it.  And since Dictator requires WP CLI we can't build Dictator in as a component of the box.  OTOH if it did not require WP CLI it would be very interesting. Maybe so much that we should consider forking it?

    That said, we do want the box to 100% support WP CLI and things like Dictator so that any user of it will be able to use it whenever and however they like.

**Comment by khromov** [comment]
@mikeschinkel I've primarily tried to showcase the specific functionality/scope of configurability based on my experience with automated Vagrant setups. 

The variable naming/structure of the JSON can surely be improved upon, I just tried to make it self-documenting.

Regarding `postprocess_hooks`, I assume they will run after WPLib has configured the PHP/Mysql version, database setup (creating db, users) and virtualhost config. 

I think they should run on `vagrant provision`, but some things will have to be examined, such as whether the user would like to re-import the `database` file or not (probably not in that case).

Regarding your thoughts:

2.) I understand wanting to make things easy, such as installing a specific version of core, but it also needs to be easy for people using a Composer workflow, ie I don't want to install WP using WP CLI, I want to do it via Composer, which is the same process that runs when I deploy to production.

3.) I agree SQL is limited, which is why I suggested Dictator. 😄 

5.) I've been following WP CLI development over the past year or so, and I respectfully disagree that it is not stable enough for production use. 

Regarding the scope of Dictator, it is primarily useful for handling settings, ie automatically configuring all the settings you need that are stored in `wp_options`. It can also add users and taxonomy terms, but it doesn't  handle content.

**Comment by mikeschinkel** [comment]
@khromov Sorry for the late reply. This feel below the radio and I missed following up until now when I got the notice of closure of the ticket.

Our first pass at this is very MVP, meaning we only list the services that we need. We've learned the only way for us to move the project forward (which we have to work on client projects) is to do it in very small increments so all of the other types of things you recommended will get discussed and/or addressed on future micro-releases.  We are very aware of critical paths and to address some of the other issues **now** would require us to take time to build things for the short term that we would later throw away.

As to specifics:

> _"I've been following WP CLI development over the past year or so, and I respectfully disagree that it is not stable enough for production use."_

Replying to this first because I think you misunderstood what I was trying to say, and I certainly do not want to be misquoted in some other forum as saying WP CLI has issues; that is not what I meant.

While I think WP CLI is a tremendous and powerful solution in the hands of a user, we don't think it will work as an _**invisible component**_ powering higher level functionality.  As a WP CLI user if you run into a problem with WP CLI because you have the wrong version of WordPress or one of your plugins that gets loaded has broken code you will likely know how to fix it or at least know how to Google for a solution.

If, on the other hand, we have a browser-based admin console that a WordPress site builder whose primary skills are using Photoshop and Dreamweaver and they go to update a site in our admin and that fails because of WP CLI, then they will have no clue how to fix it. 

By analogy, let's say you have a desktop program you download that allows you to encode videos and that program uses FFMPEG underneath.  If FFMEG has an issue with the configuration of their machine then the end user of the desktop program who has never used a command line in their life will probably have no way of knowing how to fix it.  [**Here**](https://github.com/wp-cli/wp-cli/issues/1631#issuecomment-255724267) [**are**](https://github.com/wp-cli/wp-cli/issues/2289) [**some**](https://github.com/wp-cli/wp-cli/issues/2376) [**examples**](https://make.wordpress.org/cli/handbook/common-issues/) [**of the**](https://make.wordpress.org/cli/2013/10/24/how-wp-cli-loads-wordpress/) [** types of**](https://make.wordpress.org/cli/2015/12/01/survey-results-2015/) [**problems**](https://github.com/wp-cli/wp-cli/issues) that cause of to not want to build _on top of_ WP CLI.

**Very important for us**, we are striving for two complementary product attributes 1.) _"It just works"_ and 2.) _"It doesn't break."_  The reason we do not want to use WP CLI _**as a component of**_ WPLib Box is because WP CLI can too easily be broken by custom code in a WordPress project.  That does not make it non-robust for direct use where the user can solve the occasional coding issues they stumble onto, it just makes it a poor choice for a dependency of another product that needs to be able to depend on it working 100% of the time. If you know you are using WP CLI  you can work around those issues, but if you are not directly using WP CLI then you will see it as a problem with WPLib Box and not even know that WP CLI is to blame.  

In comparison WordPress depends on both jQuery and TinyMCE, and neither of those dependencies have been without significant challenges over time.  Those challenges have been overcome because 
WordPress has an overwhelming army of contributors.  WPLib Box not so much, and so making good dependency decisions is crucial to our potential future success.

So *I am not saying WP CLI is not robust*, I am simply saying we are making a dependency decision because of our desired _"It doesn't break"_ attribute and choosing not to have our core product depend on WP CLI.  

> _"I understand wanting to make things easy, such as installing a specific version of core, but it also needs to be easy for people using a Composer workflow, ie I don't want to install WP using WP CLI, I want to do it via Composer, which is the same process that runs when I deploy to production."_

Absolutely agree with that. We 100% intend to support a Composer workflow; we currently use that workflow ourselves so there is no chance we will implement something that does not work with Composer.  

And we actually don't envision using WP CLI for creating DBs either; certainly it should be possible to use WP CLI, but we think we can simplify it. For example, if you need to add a DB for a site why not just add the DB for you when you add the site?  That said, there are a lot of things that I don't think we (my team) can envision 100% until we actually get to the point of trying to implement them, so we leave a lot of these things open ended waiting until the revision where we'll work on specific functionality.

> _"I agree SQL is limited, which is why I suggested Dictator."_

Dictator is definitely interesting.  But it has too many dependencies for our tastes, see above about WP CLI. We'll be happy to make it usable but don't want to build our functionality on top of it. That said, it is definitely something we should work within the box when our users wants to use it.
