### ISSUE TITLE
Error on vagrant up, new mac, new vagrant install

### ISSUE THREAD

**Issue by rfair404** [wplib/wplib-box#203]
> I've been dreaming of getting a new mac, and getting my local development set up in the most ideal way possible. Well, that day finally came (last week) and I quickly unboxed my shiny new toy. I updated my PhpStorm license, got bullet train oh-my-zsh theme set up, added ssh keys for github and thought I had a super slick new laptop for developing my next project on. All I was missing was a vagrant box (right). 

I had hoped to utilize wplib/wplib-box as I've heard from @mikeschinkel that it "just works" and I wanted to give it a shot on my new shiny machine. However, when I run `$ vagrant up` I get the following error. 

```
/Users/russell/.vagrant.d/gems/2.2.5/gems/trigger-0.0.1/lib/trigger.rb:49:in `method': undefined method `halt' for class `Vagrant::Config::V2::DummyConfig' (NameError)
	from /Users/russell/.vagrant.d/gems/2.2.5/gems/trigger-0.0.1/lib/trigger.rb:49:in `update_triggerable_index'
	from /Users/russell/.vagrant.d/gems/2.2.5/gems/trigger-0.0.1/lib/trigger.rb:38:in `append_triggerable'
	from /Users/russell/.vagrant.d/gems/2.2.5/gems/trigger-0.0.1/lib/trigger.rb:28:in `before'
	from /Users/russell/vagrants/rfair-wp-lib/Vagrantfile:363:in `block in <top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/config/loader.rb:113:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/config/loader.rb:107:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/config/loader.rb:107:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/config/loader.rb:104:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/config/loader.rb:104:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:746:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:746:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:492:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:214:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:479:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:728:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/bin/vagrant:130:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/bin/vagrant:130:in `<main>'
```

I am not sure if it is a Vagrant problem or not. I have successfully cloned scotch-box and got it running, so it seems that the basic vagrant systems are working. Not sure about this error, and googling it doesn't yield much by way of **solving** the issue.

Any help much appreciated. 

results of `$vagrant up --debug >> vagrant.log.txt` attached!
[vagrant.log.txt](https://github.com/wplib/wplib-box/files/900174/vagrant.log.txt)

**Comment by mikeschinkel** [comment]
@rfair404 Version of Vagrant?

**Comment by rfair404** [comment]
@mikeschinkel VirtualBox Version 5.1.18 r114002 (Qt5.6.2)
Vagrant Version 1.9.3

**Comment by mikeschinkel** [comment]
Oh, and the _"it just works"_ is more of a mantra that we think about constantly vs. any 100% guarantee that we can make, since we rely on other software.  The point of the mantra is that we always think about _"How will think new feature affect the box?  Will it increase or decrease the likelihood of breakage."_.  So as a grow feature hopefully we'll be closer to always working that occasionally breaking.

**Comment by rfair404** [comment]
Oh yeah, totally understand. I didn't interpret it to mean "guaranteed to work"

**Comment by mikeschinkel** [comment]
@clubdeuce Aer you available to look into this today?

**Comment by clubdeuce** [comment]
@mikeschinkel Unfortunately, no.

**Comment by clubdeuce** [comment]
@rfair404 Based on the output you posted, this appears to be an error in the Vagrant plugins installed.

Did you install the `vagrant-triggers` plugin found [here](https://github.com/emyl/vagrant-triggers)?

**Comment by clubdeuce** [comment]
@rfair404 WPLib Box assumes the following plugins are available:

`vagrant plugin list`

```
vagrant-hostsupdater (1.0.2)
  - Version Constraint: > 0
vagrant-triggers (0.5.3)
  - Version Constraint: > 0
```

**Comment by clubdeuce** [comment]
@rfair404 Were you able to resolve this?

**Comment by clubdeuce** [comment]
Closing this issue due to no response from original poster.

**Comment by rfair404** [comment]
Sorry for being AFK - I am in and out of reliable signal range from time to time and didn't see this before it was closed. 

Yes, I was able to get the box to work with the triggers plugin installed. Thanks for the feedback.
