### ISSUE TITLE
How do I modify the dockerized nginx configuration?

### ISSUE THREAD

**Issue by greghaygood** [wplib/wplib-box#204]
I'm getting a 413 Request Entity Too Large error when trying to upload a 2mb file. The PHP configuration appears to have been set to allow up to 100mb uploads, but I don't see how to update the client_max_body_size in nginx now that it's been docker-ized.

**Comment by tedmasterweb** [comment]
I would also like to know how to tail the log files (not sure where they are).

**Comment by greghaygood** [comment]
@tedmasterweb I can answer that one, at least...
```
docker logs -f nginx # or apache if you switched
```

**Comment by jonathanbossenger** [comment]
This article explains how to edit the nginx configuration for the Request Entity to large problem, its an nginx specific problem.

https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by mikeschinkel** [comment]
@greghaygood The short answer is you can't _(yet.)_. We realized that would be an issue but did not address it yet because we assumed that there would not be a need for only single site operation.

If you need is to just increase upload size @clubdeuce could do a quick fix and release it and we could address a way to modify the upload size later. Would that work for you?

Immediate solution is to fall back to version 0.11.

**Comment by tedmasterweb** [comment]
@greghaygood Any idea how to tail the PHP error log? I seem to recall reading somewhere that PHP errors were being sent to the web server error log. Is that true?

Thanks in advance. Really liking this project.

**Comment by greghaygood** [comment]
@mikeschinkel I did downgrade since it was holding me up on my current project. Updating the nginx docker image to match the setting on the php side makes sense as a quick fix, though.

@tedmasterweb Since I downgraded, I don't have a VM to check at the moment. Maybe @clubdeuce or @mikeschinkel will have a better answer for you?

**Comment by mikeschinkel** [comment]
@tedmasterweb @clubdeuce Would now the answer to that.  Simple questions like this might also be easier on Slack.

**Comment by clubdeuce** [comment]
@tedmasterweb The PHP-FPM logs can be found in `/var/log/php{version}-fpm.log`, _(e.g. `/var/log/php7.0-fpm.log`)_.
