### ISSUE TITLE
Implement PHP 7.1 as a Docker Container

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#207]

**Comment by clubdeuce** [comment]
Problems:

+ There are no Alpine Linux packages for 7.1 _(as of this ticket, Alpine has packages for `5.6` and `7.0`.
+ The [official docker image](https://hub.docker.com/_/php) for PHP does not have any extensions included. They need to be added manually.

Possible solutions:

+ Build our own containers using Ubuntu or Debian as the base. These distributions have packages for all three versions of PHP, but the containers will be rather large _(i.e. greater than 350MB each)_.
+ Build PHP from source. This will require an extensive learning curve.
+ Use the official Docker image and add the necessary extensions. This will require an extensive learning curve.

**Comment by mikeschinkel** [comment]
@clubdeuce What is that URL for the Alpine PHP packages?

**Comment by clubdeuce** [comment]
@mikeschinkel [Here](https://pkgs.alpinelinux.org/packages?name=php*&branch=&repo=&arch=&maintainer=)

**Comment by mikeschinkel** [comment]
@MickMakes I believe you have already handled this?

**Comment by MickMakes** [comment]
It's now in 0.16rc1
