### ISSUE TITLE
Cannot login to Adminer with HOSTNAME

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#209]
You can login to Adminer with IP address but not HOSTNAME.   Seems like we need to GRANT wildcard rights to login?

![adminer-login](https://cloud.githubusercontent.com/assets/153285/25161009/8d8bf322-2487-11e7-8712-c763412e47ca.png)

**Comment by clubdeuce** [comment]
@mikeschinkel The issue represented in the image you posted is the absence of a password.

I cannot replicate the issue title, as I am able to access the database via hostname, IP address, and container name.

**Comment by clubdeuce** [comment]
@mikeschinkel I can confirm this is an issue when using VirtualBox, but not with VMware.

**Comment by mikeschinkel** [comment]
@clubdeuce What are potential solutions?

**Comment by clubdeuce** [comment]
@mikeschinkel I have no idea. Due to the fact that it works in the VMware machine and not in the VirtualBox machine, my first assumption would be that it has to do with VirtualBox networking. However, I currently know very little about how that works. Research will be required.

**Comment by mikeschinkel** [comment]
@MickMakes We should ensure that logging in with the hostname does work.

**Comment by MickMakes** [comment]
Add adminer-docker as part of 0.16 Vagrant host, (which has this fixed).
