### ISSUE TITLE
Add php-dom extension to PHP

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#222]
I am getting this message:

    Class 'DOMDocument' not found

That's because [we don't have php-dom extension](http://stackoverflow.com/a/14395414/102699).  To fix:

    sudo apt-get install php5-dom

Which brings up a question; how can an installable page install PHP extensions?

**Comment by clubdeuce** [comment]
@mikeschinkel That is a good question. Since FPM is being delivered as a Docker container, the container itself would have to be rebuilt with the additional extension. I am not sure how we could implement that.
