### ISSUE TITLE
Add a `box restart` command

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#223]
Add a `box restart` command.

I assume you would do this by stopping all the containers and then running `box start` inside the restart script? _(But what happens if some of those containers were not ones that `box start` starts?  Like MailHog?  That said, should we add that to services as a `"mailserver"`?)_

**Comment by clubdeuce** [comment]
@mikeschinkel What is the reason for this command? What are you trying to do that requires this?

**Comment by mikeschinkel** [comment]
@clubdeuce `box start` fails if you edit the `project.json` and run it again.

By analogy:

- `vagrant up` -> `box start`
- `vagrant reload` -> `box restart`
