### ISSUE TITLE
Ensure jq 1.5 is installed

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#224]
Seems that `0.14.0` does not have `jq` installed.  Oversight?

**Comment by clubdeuce** [comment]
@mikeschinkel `jq` is installed in the box. What leads you to the conclusion it is not?

**Comment by mikeschinkel** [comment]
@clubdeuce I was trying to run `box startup` and it was failing which I traced to `jq` being missing. I installed it and it worked.

Strangely, just now I cloned and ran `0.14.0` and it ran `box startup` fine and `jq` ran by itself, also.  So I don't know why I had the problem, but I get this is a false alarm.

**Comment by clubdeuce** [comment]
@mikeschinkel Very good.
