### ISSUE TITLE
Add version support for package installations

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#226]
The end user should be able to install a specific version of a package.

This will most likely entail using git tags.

**Comment by mikeschinkel** [comment]
@clubdeuce _"Ready for QA?"_

**Comment by clubdeuce** [comment]
@mikeschinkel I do not understand your comment.

**Comment by mikeschinkel** [comment]
@clubdeuce Thank you for taking the time to answer questions her and on the other tickets.  

The question was just shorthand for the same question I asked several other places:

_"@clubdeuce Do you mind speaking to how this is "Ready for QA"; i.e. where the code is?"_

**Comment by clubdeuce** [comment]
@mikeschinkel [Here](https://github.com/wplib/box-scripts/commit/863d034fa3883864454ed5ccd3c28155a05613df)
