### ISSUE TITLE
Add Mailcatcher/mailhog integration

### ISSUE THREAD

**Issue by andreasnrb** [wplib/wplib-box#23]
I think Mailcatcher or Mailhog integration would be a nice addition and it should be enabled by default.
https://github.com/sj26/mailcatcher is used by VVV. https://github.com/mailhog/MailHog looks more interesting I think at least the UI is prettier and there is less dependencies. It also has an REST API which could be usefull if one wants to make a plugin that integrates with the debug bar.
Both Mailcatcher and MailHog have dockercontainers.

**Comment by mikeschinkel** [comment]
@andreasnrb Sounds like a good idea.  Thanks!   

@clubdeuce ?

**Comment by clubdeuce** [comment]
@mikeschinkel This had been on my mind as well. Just had not yet gotten around to investigating.

**Comment by mikeschinkel** [comment]
@clubdeuce We have a plugin for MailHog from @andreasnrb:

- https://github.com/ArtOfWP/debug-bar-mailhog

**Comment by andreasnrb** [comment]
Its still very early alpha. But it lists mails after you have added correct settings in Tools->Mailhog. Just used my vagrant ip as default currently. Will add notification and configuration test later.
