### ISSUE TITLE
Add `working-directory` property to installable.json specification

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#231]

**Comment by mikeschinkel** [comment]
@clubdeuce Do you mind explaining to @MickMakes how far you got with _
Installables?"_

**Comment by clubdeuce** [comment]
@mikeschinkel @MickMakes I got as far as implementing installables using parameters specified in the package. See [Caddy Package](https://github.com/wplib/caddy-package/blob/master/installable.json) and box scripts [package-install](https://github.com/wplib/box-scripts/blob/master/guest/cli/commands/package-install).
