### ISSUE TITLE
Implement WP-CLI as a container

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#232]
In order to get WP CLI to work better I am suggesting we move to packaging it as a container.

I am envisioning that we could package WP CLI and then be able to map the various paths that it needs to work, and the default paths could be to known working installs inside the container or to project-specific paths outside the container.

Here is the [configuration section](https://make.wordpress.org/cli/handbook/config/) for the WP CLI handbook.  The `--path=/path/to/wp-config.php` switch allows for a different wp-config.php and I envision our container would generate that based on values in `package.json`.

Obviously there is some need for discussion on the specifics here.

**Comment by MickMakes** [comment]
It's now in 0.16.0-rc.1, which will be released shortly as 0.16.
