### ISSUE TITLE
Issues after initial setup in Windows 7

### ISSUE THREAD

**Issue by televators** [wplib/wplib-box#234]
[wplib_debug_log.txt](https://github.com/wplib/wplib-box/files/999101/wplib_debug_log.txt)
Just decided to try out wplib. Followed instructions, and after the first `vagrant up` I'm getting 500 errors. Tried reloading/reprovisioning to no avail.

I'm not a network wizard so I'm not sure if it is in that realm. Vagrant is creating two virtual adapters, 'VirtualBox Host Only Network' and 'VirtualBox Host Only Network #2'.

I skimmed through the Vagrantfile and  noticed that, on line 357, it has `config.vm.provider :vmare_fusion do |vmware|`.
Is `:vmare_fusion` supposed to be `:vmware_fusion`? The 'w' is the difference, mind you. Also, why are there VMWare bits when this is configured out of the box for VirtualBox? Can that cause problems? I'm about to comment it out to see what happens but I'll be undoing, destroying, and restarting and fiddling with settings until I either stumble upon a fix or give up. Thanks!

**Comment by mikeschinkel** [comment]
@televators Sorry you are having trouble, and happy to do am much as we can to help.  

As for VMware vs. VirtualBox, we have configured it to work with both.  You can see we have the two different providers by [looking here](https://atlas.hashicorp.com/wplib/boxes/wplib/versions/0.14.0).

I believe you are correct about it being a typo, but since I never myself use VMware I am not sure if it will still work with VMware or not.  @clubdeuce uses VMware so he can speak to that.

That said, I believe it should still work with VirtualBox even with that typo.  Please do try to comment it out and try it.  I am going to see if I can recreate the problem and will comment soon either way.

If it comes to it, please [join our Slack](http://slackpass.io/wplib) and then reach out to me on Slack to do an ad-hoc screenshare so I can help you.

**Comment by mikeschinkel** [comment]
@televators Seems like it might be a [known `Vagrant`](https://github.com/cogitatio/vagrant-hostsupdater/issues/102) [edge-case bug](https://github.com/cogitatio/vagrant-hostsupdater/issues/28).

Here is the line that is failing based on the log you provided:

- [HostsUpdater.rb#L126](https://github.com/cogitatio/vagrant-hostsupdater/blob/1.0.2/lib/vagrant-hostsupdater/HostsUpdater.rb#L126)

Based on the code and error `uuid` seems to be nil.  Following that thread [it seems there is a file that may be missing](http://stackoverflow.com/questions/9434313/how-do-i-associate-a-vagrant-project-directory-with-an-existing-virtualbox-vm#comment23660947_9437813).  I am on a Mac but this is what the directory looks like when it is complete:

![apartmentguide_dev](https://cloud.githubusercontent.com/assets/153285/26031559/cbe330e6-3845-11e7-84f3-e1810b9b9a1e.png) 
_(The `.vagrant` directory above is a peer to `Vagrantfile`; e.g. both are in your project file to which you clones WPLIb Box.)_

Tracking it down it seems like maybe your `vagrant up` failed to pull down the box in its entirety or something else have cause it not to get a complete box.  Maybe try removing the box first and them adding it back with these commands?

    vagrant box remove wplib/wplib --box-version 0.14.0
    vagrant box add wplib/wplib

Be sure to follow the prompts if any come up; they _should_ be explanatory.  Please let me know if this works or if you need my help via screenshare to resolve the issue?

P.S. What versions are your Vagrant and VirtualBox?  Are they the most current versions?

**Comment by mikeschinkel** [comment]
@televators I read through your debug log from top to bottom and not being familiar with the internals of Vagrant I am not positive but it seems like Vagrant could not find `C:/Program Files/Oracle/VirtualBox/VBoxManage.exe`  Can you verify that it is there, or is possible if you installed it somewhere else?  If it is somewhere else, you probably need to [set `VBOX_INSTALL_PATH` to the actually install path](https://github.com/mitchellh/vagrant/issues/3852).

That's about as far as I can go until I hear back from you.

**Comment by clubdeuce** [comment]
@televators Is this still an issue for you?

**Comment by mikeschinkel** [comment]
Since we have not heard back from the OP on this in over 18 months we are closing this issue. Anyone feel free to reopen if you have more feedback on this issue.
