### ISSUE TITLE
Package installation should add to project.json

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#238]

**Comment by clubdeuce** [comment]
And package deletion should remove from configuration.

**Comment by mikeschinkel** [comment]
@clubdeuce As you work on `project.json`, here is [**the current state**](https://github.com/wplib/box-cli2/blob/master/cmd/project/cmd/init/init.sh#L157) of it for what I am working on for the new box cli, and I am building up/have built up a lot of CLI code around it so hopefully we can stay in sync on it?

**Comment by clubdeuce** [comment]
@mikeschinkel The link to your current `project.json` is broken.

**Comment by mikeschinkel** [comment]
@clubdeuce I changed the command name from `box project init` to `box project create`, which broke the link.  But I fixed the link just now.

**Comment by mikeschinkel** [comment]
@clubdeuce Do you mind speaking to how this is _"Ready for QA"_; i.e. where the code is?

**Comment by clubdeuce** [comment]
@mikeschinkel [Here](https://github.com/wplib/box-scripts/commit/30e0f651d11c453d3203f2f4383f0f96d0e54189_
