### ISSUE TITLE
How to install plugins to content/plugins folder on box/composer install

### ISSUE THREAD

**Issue by baselbers** [wplib/wplib-box#246]
I am developing plugins for WooCommerce plugin, so I would like to add a few plugins to composer.json file. I need them to be installed on box installation. How can I achieve this? When I add like below the wordpress-importer plugin is only added to the 'vendor/wpackagist-plugin' folder.

```
"require-dev": {
    "wpackagist-plugin/query-monitor": "*",
    "wpackagist-plugin/helpful-information": "*",
    "wpackagist-plugin/wordpress-importer": "*"
  },
```

**Comment by clubdeuce** [comment]
@baselbers Based on the snippet above, you have done everything correctly. This is a result of #236. We are working to resolve that issue.

I am going to close this issue and suggest you follow #236.
