### ISSUE TITLE
Add `box version` command

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#248]
Add `box version` command.  Ideally it should be able to report on versions retroactively if there is enough evidence in the past boxes for you to discover them, at least back to 0.11.

In the case you can't discover, report a range like `<0.11` or `0.12-0.13`.  

But from now on report the real version, include bug fix increments.  Store in `/box/VERSION` maybe?

**Comment by clubdeuce** [comment]
@mikeschinkel  The file `/box/version` already exists. It was added in version `0.11.0`. Unfortunately we were not really using it previously, as a result it did not get incremented until `0.14.0`.

**Comment by mikeschinkel** [comment]
So the `box` command could sniff out (at least major) versions for `0.12.0` and `0.13.0` and update the file, right?

**Comment by clubdeuce** [comment]
@mikeschinkel At first glance, my answer would be *_no_*.   We could look for the existence of certain box commands _(which appeared at specific releases)_, and determine that a box is at least a certain version. However, with the upcoming refactoring of the CLI, that will only be reliable for a short term.

My inclination is to simply have the CLI be able to determine `<0.11.0`, `0.12.0 or 0.13.0` and everything from then on would have the specific version available.

**Comment by mikeschinkel** [comment]
I will be using all the guts of the existing commands when I refactor, so refactoring should not be a consideration here.

Really we are just talking about `0.12.0` vs `0.13.0`, right? Seems like we just need to look for Docker containers and if not there it is `0.11.*`. If there is a MariaDB container then it is `0.13.*` otherwise it is `0.12.*`. And if no `/box/version` then it is `<0.11.0`, right?

P.S. I think we also need a BOXCLI version file too, since it can be updated for an older box.

**Comment by clubdeuce** [comment]
@mikeschinkel What makes looking for Docker containers better than looking for a command file?

**Comment by mikeschinkel** [comment]
@clubdeuce The commands are in a git repo which can easily be updated, no?

**Comment by MickMakes** [comment]
It's now in 0.16.0-rc.1, which will be released shortly as 0.16.
