### ISSUE TITLE
TTFB ~ 10 seconds after idle

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#253]
TTFB (Time To First Byte) is taking about 10 seconds.

It seems to be responding instantly if it has been within a minute or so of the last request. But if it has been more than a few minutes it take ~10 seconds again.  Does the proxy has some kind of 10 second timeout to set things up and it is failing for 10 seconds and then just runs the default or something?

**Comment by clubdeuce** [comment]
@mikeschinkel Not that I am aware of. I am not able to replicate this issue.

**Comment by mikeschinkel** [comment]
@clubdeuce This was a configuration error on my computer.  My bad.

**Comment by clubdeuce** [comment]
@Mikeschinkel Very good.
