### ISSUE TITLE
Implement Composer as Docker container

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#255]

**Comment by mikeschinkel** [comment]
@MickMakes This was tagged as _"Ready for QA"_ by @clubdeuce but I do not see a repo for it.  

@clubdeuce do you mind speaking to the status of this so we can figure out how to pick up where you left off?

**Comment by clubdeuce** [comment]
@mikeschinkel Please see [here](https://github.com/newclarity/wplib-box-packer/commit/db931facba36906b9ac4b66c40dfbb84af05d073)

**Comment by MickMakes** [comment]
It's now in 0.16.0-rc.1, which will be released shortly as 0.16.

**Comment by mikeschinkel** [comment]
See #504 - Reimplement Composer as a (PHP) ScriptComponent
