### ISSUE TITLE
ctype extension is not active

### ISSUE THREAD

**Issue by Shelob9** [wplib/wplib-box#265]
I'm getting a fatal error for `ctype_alnum()` not defined.

 config.vm.box_version = "0.15.0"

**Comment by mikeschinkel** [comment]
Can you provide the full context of the error message?

**Comment by Shelob9** [comment]
I got the error `Call to undefined function Illuminate\Session\ctype_alnum()` 

It was triggered here: https://github.com/illuminate/session/blob/master/Store.php#L557

PHP should have called it in global namespace.

I can't find the error now, but I had same problem with socket_create() as well.

**Comment by mikeschinkel** [comment]
From PHP manual: If ctype is not enabled by default on your server, replace ctype_alnum($var) with preg_match('/^[a-zA-Z0-9]+$/', $var).

Can you create a ctype_alnum() function with the above so we can add this fix to the next release?

**Comment by Shelob9** [comment]
I already did that work around:) Just wanted to make you aware. Would be
cool to have extension settings easy to change.

**Comment by mikeschinkel** [comment]
> Would be cool to have extension settings easy to change.

That is one of the key things we plan to work on for next release.

**Comment by naomicbush** [comment]
Just ran into this issue with a new dev I was trying to get onboarded with the box

**Comment by mikeschinkel** [comment]
@naomicbush @Shelob9 Good news _(soon.)_  We finally have a new developer for WPLib Box and he is working on a new release to, hopefully to solve a lot of lingering problems, before year end.  

cc @MickMakes Can you add [CType extension](http://php.net/manual/en/book.ctype.php) to the PHP containers you are updating?  I believe it is `php{version}-ctype`, e.g. `php70-ctype`.

Also this is a great example of why we need to enable WPLib Box users to **_easily_** specify the specific extensions they are most interested in using within our PHP containers as we'll never be able know in advance all of the ones they will need.

**Comment by MickMakes** [comment]
@mikeschinkel, yup certainly will. I think we discussed this in last week's meeting.

**Comment by MickMakes** [comment]
It's now in 0.16.0-rc.1
