### ISSUE TITLE
Invalid permissions for uploads

### ISSUE THREAD

**Issue by Shelob9** [wplib/wplib-box#266]
I can not create uploads using `wp_handle_upload()` I get WP_Error with the message `The uploaded file could not be moved to uploads/2017/08.`

I tried vagrant ssh into server and chmod 777 on wp-content/uploads but no luck

**Comment by Shelob9** [comment]
Running `chmod -R 777 uploads` from host machine seems to have resolved this.

**Comment by mikeschinkel** [comment]
@Shelob9 Thanks. We'll add this to our list.  See #267.

**Comment by mikeschinkel** [comment]
@MickMakes - Can we get these fixed for version `0.16.0`?

<img width="1028" alt="cannot-upload_png" src="https://user-images.githubusercontent.com/153285/34374753-b6412504-eab0-11e7-9ccb-28f8fc0f8b32.png">
<img width="1033" alt="cannot-install-plugins" src="https://user-images.githubusercontent.com/153285/34374757-bdb3c742-eab0-11e7-8076-4f04160e4fdf.png">

**Comment by mikeschinkel** [comment]
@MickMakes See #245 also - it is a duplicate but may have some helpful info.

**Comment by MickMakes** [comment]
It's now in 0.16.0-rc.1, which will be released shortly as 0.16.
