### ISSUE TITLE
Update documentation for 0.16.0

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#269]
This should include both:

1. Items @MickMakes recognized are confusing or insufficient. 
2. Items that are now wrong and need to be updated for `0.16.0`.

Also, should we go ahead and publish using [GitHub pages](https://pages.github.com/) at https://wplib.github.io/wplib-box/ instead of in the README and FAQ?

**Comment by MickMakes** [comment]
GitHub pages - yes. Currently I'm going to put this one on hold until later in the week as we need to get 0.16.0 out the door.
