### ISSUE TITLE
Proxy to web server HTTP/HTTPS auto-config.

### ISSUE THREAD

**Issue by MickMake** [wplib/wplib-box#277]
Provide a mechanism that allows a user to switch between different operational modes:
* client (http) -> (http) web server.
* client (http) -> proxy -> (http) web server.
* client (https) -> (https) web server.
* client (https) -> proxy -> (https) web server.

**Comment by mikeschinkel** [comment]
We may need to tackle this for `0.16.0`.  See #321

**Comment by MickMakes** [comment]
This is a little more complex to be in 0.16.0.
It'll require a major change to the way Docker containers are handled. IE: Dynamically change container configs to point to new end point.

**Comment by mikeschinkel** [comment]
We are unsure if this is still needed because #321 is closed, so closing for now.
