### ISSUE TITLE
Have Box Scripts auto update for patches on startup/reboot

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#279]
This for next release, might be changed after that.

So if Box Scripts version in the box is `0.16.0` and the GitHub repo has `0.16.1`, `0.16.2`, `0.16.3` ... `0.16.x` then it will update to latest version using a `git pull`, but only on box startup/reboot.

It will NOT update Box Scripts to version `0.17.0` if `0.16.x`.

**Comment by MickMakes** [comment]
Auto-update script created and added to box-scripts - just need a method to properly determine the 'when'.
