### ISSUE TITLE
Work with older project.json values for 0.16.0

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#280]
Old values _(for example):_

    {
      "services" : {
        "database": "mysql",
        "webserver": "nginx",
        "processvm": "php7",
        "kvstore": "redis"
      }
    }

New values _(for example):_

    {
      "services" : {
        "database": "mysql-5.7.21",
        "webserver": "nginx-1.13.8",
        "processvm": "php-fpm-7.1.9",
        "kvstore": "redis-4.0.7"
      }
    }

**Comment by mikeschinkel** [comment]
Actually, if at all possible, I'd like to have the simpler version be the canonical version of `project.json`.

**Comment by MickMakes** [comment]
A new script 'readJSON' handles all the guess work of different JSON versions. It also pulls in default defined under /opt/box/etc/releases/X.XX/project.json files.
