### ISSUE TITLE
Create Composer docker container.

### ISSUE THREAD

**Issue by MickMakes** [wplib/wplib-box#288]
And provide latest release 1.6.3. Also provide 1.5.6 and 1.4.3.

**Comment by mikeschinkel** [comment]
So this looks good for `0.16.0`, **however** Composer wants to run in the PHP context so there are a couple things we should look at doing in a future release.  

For this release I think we should run Composer with the `--ignore-platform-reqs` flag, but for later version I think we should be able to specify in `project.json` _(and in `composer.json`)_ the context in which is should run; PHP version, etc.  I will create a new ticket for that.

**Comment by mikeschinkel** [comment]
See #504 - Reimplement Composer as a (PHP) ScriptComponent.
