### ISSUE TITLE
Update default database for 0.16.0

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#311]
The default database needs to be updated to support:

1.) The latest version of WordPress _(run db upgrade script)_
2.) The [Welcome theme](https://github.com/wplib/wplib-box/issues/274) as the initial theme.
3.) Preactivate the [WPLib Box Support plugin](https://github.com/wplib/wplib-box/issues/309) _(which is currently in `mu-plugins` but needs to be moved to `plugins`.)_

**Comment by mikeschinkel** [comment]
Also, is there an easy way we could enable import of a SQL dump on first `vagrant up` to replace the default database if one is included in the distribution package?

**Comment by MickMakes** [comment]
3. Remove wp-redis from mu-plugins dir and move wplib-box-support over to content/plugins.

**Comment by mikeschinkel** [comment]
@MickMakes I am getting the following when running `mysqldump`:

mysqldump: Couldn't execute 'SHOW VARIABLES LIKE 'gtid\_mode'': Table 'performance_schema.session_variables' doesn't exist (1146)

**Comment by MickMakes** [comment]
@mikeschinkel I never answered your question `Also, is there an easy way we could enable import of a SQL dump on first vagrant up to replace the default database if one is included in the distribution package?`
Yes this has been implemented. The /vagrant/provision directory houses the template for a newly created DB.

**Comment by mikeschinkel** [comment]
For my near future reference: https://github.com/wplib/box-scripts/tree/0.16.0-rc.2/etc/releases/

**Comment by mikeschinkel** [comment]
Update is here:  https://github.com/wplib/box-scripts/tree/0.16.0/etc/releases/0.16.0/sql
