### ISSUE TITLE
Using https URLs but REQUEST_SCHEME shows http.

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#321]
@MickMakes I think there may be a problem with `$_SERVER['REQUEST_SCHEME']`.  I am calling a `https://` URL and just ignoring the errors and the first line in the PHP file that loads in `XDEBUG` shows `$_SERVER['REQUEST_SCHEME']` as equal to `'http'`.

Is this because of the proxy recognizing that it is not really `https` and thus calling NGINX with `http`?    

Version `0.16.0-rc`

Options:  

1. Pass `$_SERVER['REQUEST_SCHEME']=='https' on the the web server even if not real HTTPS`.
2. Get SSL working in the box whenever `https` is used. (See #165)
3. Something else I don't know enough to suggest.

**Comment by MickMakes** [comment]
Proxy configured for https and http separately.
