### ISSUE TITLE
Switch to mysql-5.5.59 container as default for 0.16.0

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#329]

**Comment by tedsecretsource** [comment]
I'm having issues too. #170 in particular. Unable to bring up the vagrant box. The solution pointed to in that case doesn't work for me either. I have no idea how to fix this…

**Comment by mikeschinkel** [comment]
@tedsecretsource This ticket would not be the default case so it would not be your issue. I am checking #170 now.

**Comment by mikeschinkel** [comment]
Change name of this ticket. Used to be _"mysql-5.5.59 container won't start in 0.16.0-rc"_

**Comment by MickMakes** [comment]
5.5.59 is now the default, (subsequent revisions can now use the /opt/box/etc/releases/X.XX/project.json files).
