### ISSUE TITLE
Disable "You can install by typing..."

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#338]
Here is what it looks like what I typed `phpunit`, as you would expect:

![apt-get_phpunit](https://user-images.githubusercontent.com/153285/36639238-35057166-19d6-11e8-9eaf-31571457af2b.png)

Since we want to move away from having anyone install anything locally we should disable this.

Additionally I think it would be good if we could instead ask if they would be okay sending us a message explaining why they need it so we can consider adding it.

Also, of course, if we have it to be optionally added we could also provide them an alternate message such as _"You can install this by typing `box install <whatever>`"_

**Comment by MickMake** [comment]
Removed this from the base VM.
