### ISSUE TITLE
VMWare Fusion / Workstation support

### ISSUE THREAD

**Issue by khromov** [wplib/wplib-box#34]
Would be nice to have VMWare Fusion / Workstation support. The Vagrant box needs to be packed differently for those: https://www.vagrantup.com/vmware/

**Comment by mikeschinkel** [comment]
@khromov Thanks for the request.

Theoretically is supports VMware, though we have not been testing with it.  Can you test?

**Comment by khromov** [comment]
@mikeschinkel The box needs to be packaged separately and uploaded to Vagrant Cloud with the VMWare Fusion or Workstation provider.

See:
https://www.vagrantup.com/docs/vmware/boxes.html

**Comment by mikeschinkel** [comment]
@khromov Yes, we know.  Looking now it seems we had one for the earlier version of the box _(which was never really workable):_ 

- https://atlas.hashicorp.com/wplib/boxes/wplib

So I will add a request for @clubdeuce to make sure we have the VMWare version updated whenever he updates the VirtualBox version.

**Comment by mikeschinkel** [comment]
@khromov So we have to buy some software evidently to make this work, $180.  We've decided to go ahead and buy it so we can support VMware.

**Comment by khromov** [comment]
Awesome! We recently abandoned Virtualbox because of the slowness of synced folders, see:
http://mitchellh.com/comparing-filesystem-performance-in-virtual-machines

With VMWare Fusion went from WordPress load time of 2-5 seconds down to 0.5-0.8, which was a big productivity increase for us.

**Comment by mikeschinkel** [comment]
@khromov Cool.  I have heard of similar improvements.  Myself, I wanted to stick with what most people will start with otherwise -- VirtualBox -- otherwise I won't appreciate the initial experiences with out box.

So we can expect you to beta test it for us?  :-)

**Comment by khromov** [comment]
@mikeschinkel You bet! Just @ me when it's ready and I'll give it a spin! :facepunch:
