### ISSUE TITLE
Install Imagick and Pcntl PHP extensions

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#343]
@MickMakes This is a very common PHP extension and should be installed by default.  PCNTL is required by `phpunit/php-invoker` which is a recommended add-on for PHPUnit.

- http://php.net/manual/en/imagick.installation.php
- http://php.net/manual/en/pcntl.installation.php

![1__vagrant_grapeconnect___vagrant__ssh_](https://user-images.githubusercontent.com/153285/36928593-201b5878-1e55-11e8-91a4-c97469fedece.png)

**Comment by MickMakes** [comment]
I figure that this is something that would be highly sought after. So, I'll add it in to the php-fpm containers - it might bloat them though.

**Comment by mikeschinkel** [comment]
@MickMakes Please document here in GitHub issues which containers support these two and which do not.

**Comment by MickMakes** [comment]
5.5.x and 7.1.x both support PHP ImageMagick. 7.0.x can't be enabled, (easily), and so this version will be made available in 0.17.

**Comment by mikeschinkel** [comment]
WPLib Box Support plugin - Add those functions and note when PHP 7.0 and 7.2 tries to use them.

**Comment by MickMake** [comment]
Added to all PHP containers: 5.2.4, 5.3.29, 5.4.45, 5.5.38, 5.6.36, 7.0.30, 7.1.18 & 7.2.6.
