### ISSUE TITLE
Put the WordPress Starter Site for the Box in a Repo

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#35]
Per a question on Facebook asking it we are going to open source the _"WP-specific config of the built box"_ I think we should create a repo for the starter site, such as:

- `wplib/site-box-single`

Then we can manage this separately from the box packer?

**Comment by clubdeuce** [comment]
@mikeschinkel we can do that.

**Comment by mikeschinkel** [comment]
After discussing with @clubdeuce this goes against the idea of having an "appliance" in the box repo that "just works", i.e. that does not require running composer first.
