### ISSUE TITLE
Support only latest major version of WP CLI

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#360]
In talking with the WP CLI team they only officially support the latest version so I don't think we need to maintain `wp-1.0`, `wp-1.1` etc. in the bin directory.  When the release 2.0 we could support `wp-1.x` being the latest version 1.0 series.

Then we can monitor and see if any users need more specific versions, but I kinda doubt it.  Doing this will reduce some of the bloat in the `/opt/box/bin` directory.

They have said they will use the tag `breaking-changes` in their GitHub issues when they make backward incompatible changes.  We could monitor those on each release if we wanted to be extra certain.

**Comment by MickMake** [comment]
Removed all but the latest.
