### ISSUE TITLE
W004 error triggered when PHP generates a 5xx error.

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#361]
So I think I have enough evidence to say that these errors are being triggered by a PHP error that generates a 5xx status code.  

```W004 - php-fpm Docker container not running.
The php-fpm Docker container may have been shutdown for some reason or is not starting up properly, or network connectivity is an issue.
Look for possible fixes here: https://github.com/wplib/wplib-box/tree/master/docs/errors/W004```

We need to find a way to ensure the errors do not have false positives because a 500 says _"my code is bad"_ but a "W004" says "My WPLib Box is broken," which is obviously not the message we want to send.

**Comment by MickMake** [comment]
Changed the error code to reference a generic "500 HTML error code" and added it to the docs.
Finding a better way to determine if the php-fpm container is down.

**Comment by mikeschinkel** [comment]
@MickMake Is that _"500 HTML error code"_ or did you not really mean _"500 *HTTP* error code?"_

What did you actually use?

**Comment by MickMake** [comment]
Changed error code to display W020 instead of W004 - https://github.com/wplib/wplib-box/tree/master/docs/errors/W020
