### ISSUE TITLE
Add `sendfile off;` to nginx config

### ISSUE THREAD

**Issue by sarutole** [wplib/wplib-box#37]
Evidently, to avoid illegal tokens appearing in the middle of  concatenated JS files we need to have sendfile set to off. Ref: http://stackoverflow.com/questions/12719859/no-visible-cause-for-unexpected-token-illegal/23487194#23487194

**Comment by greghaygood** [comment]
+1 

I just ran into this when the VM wasn't picking up changes to the CSS file from my IDE.

http://www.falexandrou.com/2014/02/13/vagrant-apache-or-nginx-serving-corrupt-javascript-and-css-files/
