### ISSUE TITLE
Move box-scripts to `/opt/box/cli`

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#375]
The reason for this is to allow `/opt/box` to contain other things that will not be updated during `box self-update`

**Comment by MickMake** [comment]
This is no longer required as I was able to fix the self-update script.

**Comment by mikeschinkel** [comment]
@MickMake I was not just because of the `self-update`, it was also to better organize the directory.

**Comment by MickMake** [comment]
OK. Everything moved to /opt/box/cli to accommodate an /api directory for Orca.
