### ISSUE TITLE
Resolve issues with `box self-update`

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#376]
Currently it moves `/opt/box` directory aside and then does a `git clone` but should do a proper git sync.

**Comment by MickMake** [comment]
Finally resolved all the scenarios that blocked updates:
* Tracked files that may be modified by a user - Overwrite with GitHub.
* Tracked files that are modified by a user, but deleted in a newer branch/tag - Overwrite with GitHub.
* Untracked files that are added by a user/script - keep.
