### ISSUE TITLE
Enable PHP to read box version

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#384]
I need to be able to read the current box version from PHP so I can display it in the Welcome Theme and don't have to worry about updating the theme for every minor new version.

I tried reading `/opt/box/version` but permissions disallows that.
I looked in `$_ENV` but it is not in there anywhere.
I tried doing `exec( 'box version' )` but that did not work either.
I even tried doing `exec( 'sudo cat /opt/box/version' )` but clearly that did not work.

How can I get the current box version from PHP?

**Comment by MickMake** [comment]
Export ENV variable.
Try and think of any other variables while we're doing this.

**Comment by mikeschinkel** [comment]
This will be handled by #399.
