### ISSUE TITLE
Need `mysql` command line script similar to PHP & WP-CLI.

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#393]
Obviously this will need to call Docker but it should allow running mysql commands just as it the `mysql` command line tool was installed it the VM.  This also needs we need superuser access.  And no passwords required, please.

**Comment by mikeschinkel** [comment]
This needs to provide super user capability to `vagrant` user.

**Comment by MickMake** [comment]
mysql command provided. Also fixed that nagging STDIN issue that was hanging around.
