### ISSUE TITLE
Revert back to JQ 1.5

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#407]
Somehow we have a regression from #224 and [`JQ`](https://stedolan.github.io/jq/) is at version `1.3` vs. the latest release: `1.5`.

**Comment by MickMake** [comment]
Moved to https://github.com/newclarity/wplib-box-packer/issues/16

**Comment by MickMake** [comment]
JQ 1.5 was removed back in 0.16.0 along with the big clean-out of stuff.
