### ISSUE TITLE
mysql command broken when MariaDB 10.3 selected in project.json

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#423]
Typing `mysql` fails with MariaDB 10.3

**Comment by mikeschinkel** [comment]
Now MariaDB is throwing this error:

```ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")```

**Comment by MickMake** [comment]
Resolved in #455
