### ISSUE TITLE
Disable Linux "help" that suggests installing via apt-get

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#428]
Since the plan for WPLib Box is to extend via containers these _"helpful"_ suggestions are actually harmful for us to help recommend best-practices for our users:

![_no-_help](https://user-images.githubusercontent.com/153285/41198039-23a7fbf0-6c3d-11e8-8d06-cd6b263b3ca0.png)

Minimally is should have say something like `"xxxxx command not found."`  Ideally it should provide suggestions on our to extend via containers.

**Comment by mikeschinkel** [comment]
@MickMake Just tested and still not fixed.

**Comment by MickMake** [comment]
Not sure why it's not fixed with your env. The Packer script, (04-dep.sh), is definitely removing it.
`apt-get -qy remove command-not-found-data command-not-found`
Maybe you picked it up before the push...
