### ISSUE TITLE
Running mysql script fails on remote connection(?)

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#438]
In trying to run a complex command to connect to a remote server I get an error that the container cannot be installed _(see screenshot):_  

![mysql-fail](https://user-images.githubusercontent.com/153285/41504739-fcb288dc-71c6-11e8-9214-6181ffe86a85.png)

However if I run just `mysql` that works.

`project.json` is:

    "services": {
        "database": "wplib/mysql:5.5.60",
        "webserver": "wplib/nginx:1.13",
        "processvm": "wplib/php:5.6.36",
        "kvstore": "wplib/redis:4.0"
    }

**Comment by mikeschinkel** [comment]
Apply to `msqldump` too.

**Comment by MickMake** [comment]
Resolved in #455
