### ISSUE TITLE
Remove mention of Ubuntu in login screen

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#450]
Let's remove the following mention of Ubuntu in the login screen:

    This WPLib Box is based on:

        - Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)

Reasons, in order of importance:

1. It is not an much older version of Ubuntu than is shipping and though we have decided there is no benefit in upgrading people might see it and be intuitively turned off.
1. We are moving to Alpine or Tiny Core in `0.18.0` anyway, so no need to set an expectation.
1. It takes up space on the screen.

**Comment by MickMake** [comment]
Removed in box-scripts.

**Comment by MickMake** [comment]
Removed from MOTD.

**Comment by mikeschinkel** [comment]
Fixed.
