### ISSUE TITLE
On change of project.json, new component w/only major.minor takes .patch# of prior component

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#453]
On change of `project.json`, new component w/only `major`.`minor` takes `.patch`# of prior component:

## Example:

Prior box configuration:   

    "wordpress/dbserver": "wplib/mysql:5.5.60"

New box configuration:   

    "wordpress/dbserver": "wplib/mariadb:10.3"

`box restart` will try to start this container 
_(it adds MySQL's `.60` to `10.3` instead of looking for the latest patch for `mariadb:10.3`):_

    wplib/mariadb:10.3.60

**Comment by MickMake** [comment]
Updated get_latest_patch_version() to grep versions.
