### ISSUE TITLE
0.17.0-rc: MySQL 5.5.60 failing to start

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#465]
Note the Stripping `'520'` is not an error and is running as designed.  The error here is lack of communication with MySQL.

![mysql-dead](https://user-images.githubusercontent.com/153285/42297301-83f60c20-7fcc-11e8-9915-daccf67e920c.png)

**Comment by mikeschinkel** [comment]
it is possible because of permission denied on `provision` files as seen here in `box-restart`?

![perm-deny](https://user-images.githubusercontent.com/153285/42297333-c56c40fc-7fcc-11e8-9f19-740cb6e0b87c.png)

**Comment by mikeschinkel** [comment]
@MickMake It appears this issue is the fact that permissions were denied when trying to copy over the `provision` files.  I added `sudo` and it seemed to fix it, but I assume it should not require `sudo` and maybe you need to do something else?  Please review this and either accept or implement a different fix.

**Comment by MickMake** [comment]
Mike,
The permissions are actually fine. The issue is that the Wordpress DB dump has `utf8mb4_unicode_520_ci` within it. 

```
180705  5:12:05 [Warning] 'proxies_priv' entry '@ root@ad42c7a6ae6c' ignored in --skip-name-resolve mode.
180705  5:12:05 [Warning] 'proxies_priv' entry '@ root@ad42c7a6ae6c' ignored in --skip-name-resolve mode.
/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/README.md
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/provision.sh
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/provision.sql
ERROR 1273 (HY000) at line 25: Unknown collation: 'utf8mb4_unicode_520_ci'
```

Confirmed this by changing all these references within a copy of the official provision.sql file.

utf8mb4_unicode_520_ci -> utf8_general_ci
utf8mb4 -> utf8/g

**Comment by MickMake** [comment]
The DB import was in a race with the MySQL container import. Disabled MySQL container importing in favour of component scripts.

**Comment by mikeschinkel** [comment]
Fixed.
