### ISSUE TITLE
0.17.0-rc: http://docs.wplib.box is not serving from `{project}/docs`

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#466]
When I try to load docs.wplib.box in the browser is gives the following error:
 
<img width="907" alt="mkdocs-fail" src="https://user-images.githubusercontent.com/153285/42297848-4a701b90-7fd0-11e8-8c9c-ef7e6951458d.png">

**Comment by MickMake** [comment]
Was left out of the project.json release file.

**Comment by mikeschinkel** [comment]
Done.
