### ISSUE TITLE
Move `box first-time-provision` into `box startup` [0.17.1]

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#468]
`box first-time-provision` complicates the `Vagrantfile` and since the beginning I wan't to keep complication at a minimum.  Thus I'd prefer to have `box first-time-provision` less visible.

**Comment by MickMake** [comment]
"Ready for QA" tests:
* `rm /etc/box-scripts-updated` - remove FTP file.
* `vagrant halt` - shutdown VM.
* `vagrant up` - startup VM.
* `ls -l /etc/box-scripts-updated` - if file exists, FTP has been executed.

**Comment by mikeschinkel** [comment]
@MickMake - _" if file exists, FTP has been executed."_

FTP?

**Comment by mikeschinkel** [comment]
@MickMake Anyway, looks good.   

Not sure about the full component list at the end. I think it is **TMI**.

 Remember what the WordCamp attendees felt about Docker and containers?

**Comment by mikeschinkel** [comment]
@MickMake While better, I don’t think its the right result for `box status`.  

Seems to me if I am looking for status I’d want to know what is running more that what is installed.  Maybe we have a `- -installed` switch for the user to list what is installed?  Or a `box status running` vs. `box status installed`, even better.

**Comment by mikeschinkel** [comment]
This is moot since moving to `.vagrant/box.rb`.
