### ISSUE TITLE
Stop box from backing up on `box startup` [0.17.1]

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#470]
Add `--no-backup` switch on `box database import provision.sql`

![import](https://user-images.githubusercontent.com/153285/42358181-596738de-80a9-11e8-9b42-ef7d444cbef6.png)

**Comment by mikeschinkel** [comment]
@MickMake Looks good per the original concern.  

What is the purpose of `sql/provision.sql.lock`, and given our discussion about the collective distaste for `.lock` files, is this the only approach?

**Comment by MickMake** [comment]
Currently it is used to merge the `official` json file with the user's json file. So, at least for 0.17.1 without big changes), it's the approach that works, (but not the only one).

**Comment by mikeschinkel** [comment]
@MickMake I don't follow.  A _"sql"_ lock file is being used to merge _"JSON?"_

**Comment by MickMake** [comment]
provision.sql.lock is now being created on the VM filesystem.

**Comment by mikeschinkel** [comment]
This appears to be complete.
