### ISSUE TITLE
composer fails with `unable to find user wplibuser` [0.17.1]

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#473]
First look at how we could potentially move all reference to use to a configuration file, and if the scope of that is too large create new ticket for it and to at a later milestone:

![wplibuser](https://user-images.githubusercontent.com/153285/42417731-38c62c2c-825f-11e8-866d-3f1b11b992ca.png)

**Comment by mikeschinkel** [comment]
See #504 - Reimplement Composer as a (PHP) ScriptComponent.

**Comment by MickMake** [comment]
"Ready for QA" test:
* `box self-update 0.17.1` - update box-scripts.
* `box container uninstall wplib/composer:1.6.4` - ensure it's not present.
* `composer` - install and run composer.

**Comment by mikeschinkel** [comment]
![merge-conflict](https://user-images.githubusercontent.com/153285/43488409-a4678c9c-94e7-11e8-9c0b-d400b76ac766.png)

**Comment by mikeschinkel** [comment]
@MickMake The above seems to be me copying and using your comment.  Without the comment the `box self-update` works.  However, running `composer init` interactively provided this error:

![composer-init](https://user-images.githubusercontent.com/153285/43488630-56a5c342-94e8-11e8-9d5a-d14c99082576.png)

**Comment by MickMake** [comment]
This is actually a difficult problem to solve in the current architecture.
The problem arises from the use of the transient $PWD. This has been fixed temporarily to `/projects/wplib.box`

I really don't like it and it needs to change in the mid-term. Let's discuss this.

**Comment by mikeschinkel** [comment]
![latest_error](https://user-images.githubusercontent.com/153285/43750921-a4fcfee0-99c8-11e8-8c36-cf74965caab5.png)

**Comment by mikeschinkel** [comment]
Looks good.
