### ISSUE TITLE
WP CLI does not work if `wordpress/cliapp` not in stack

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#474]
WP CLI does not work if `wordpress/cliapp` is not in the `project.json` stack.

Look at the source for `/opt/box/bin/wp` we have:

    readJSON
    WPCLI="${STACK[wordpress/cliapp]}"

This should to change to:
    
    WPCLI="$(get_component_name "wordpress/cliapp")"

And then `get_component_name()` should have the logic built-in to pull from either the `project.json` or the _(future)_ global `box.json` configuration.

**Comment by mikeschinkel** [comment]
Short term let's add an error message that says you need to add to your stack.

**Comment by MickMake** [comment]
"Ready for QA" tests:
* `box self-update 0.17.1` - make sure you have the latest.
* Remove wp-cli out of project.json.
* `wp config list` - test command.

**Comment by mikeschinkel** [comment]
@MickMake This looks good.  Will let you close.

**Comment by mikeschinkel** [comment]
Seems to be working.
