### ISSUE TITLE
Enable `index.html` vs. just `index.php` [0.17.1]

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#475]
MkDocs generates `index.html` documents which it expects to be picked up by the server as a valid document.  So we cannot test an `mkdocs build` using Nginx or Apache because of this.

**Comment by MickMake** [comment]
"Ready for QA" tests:
* Create an index.html file under the www/ directory.
* Fetch http://wplib.box/index.html & https://wplib.box/index.html - confirm they are accessible.

**Comment by mikeschinkel** [comment]
**Working with Nginx:**
- `wplib/nginx:1.12.2`
- `wplib/nginx:1.13.12`
- `wplib/nginx:1.14.0`
- `wplib/nginx:1.13.12`

**But does not work on Apache**:
- `wplib/apache:2.4.33`

<img width="290" alt="apache" src="https://user-images.githubusercontent.com/153285/43488130-b1a8f46e-94e6-11e8-9bb2-b7b0215be85f.png">

**Comment by MickMake** [comment]
"Ready for QA" additional tests:
* Edit project.json file and change webserver to `wplib/apache:2.4.33`.
* `box restart`
* Test with mkdocs directory.

**Comment by mikeschinkel** [comment]
![later](https://user-images.githubusercontent.com/153285/43749951-25afc540-99c4-11e8-9135-98b83f14e0cb.png)

**Comment by mikeschinkel** [comment]
Apache is returning `file not found.`

**Comment by mikeschinkel** [comment]
Seems to be fixed now.
