### ISSUE TITLE
`wp cli` is broken - cannot find WordPress 

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#477]
Version `0.17.0`

![wp-cli-fail](https://user-images.githubusercontent.com/153285/42436382-ba5c5cde-8327-11e8-8cf6-cdc90db1686e.png)

**Comment by MickMake** [comment]
"Ready for QA" tests:
* `box component uninstall wplib/wp-cli:1.5.1` - remove existing install.
* `box component start wplib/wp-cli:1.5.1` - download, install & configure new install.
* `wp plugin list` - Display available plugins.

**Comment by mikeschinkel** [comment]
@MickMake This looks good. Will let you close.
