### ISSUE TITLE
Eliminate need to run `composer.install` before `vagrant up` but still have a working initial site

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#48]
Some of the goals for WPLib box are: 

1. It should provision as fast as possible
2. Failure of provisioning should not be possible, or at least greatly eliminated.
 
Running anything complicated for provisioning, or running anything that could potentially fail during provision then goes counter to these goals.  Examples of things that could fail:

1. Any script that needs to download software from the internet to be able to install it.
2. Any script that might download newer versions of software that has not been testing to work in the box.

That means we cannot run anything more complex than a simple Bash script that downloads nothing for provisioning.  

Thus to eliminate the need to run `composer install` -- inside the box or out -- we should copy a ZIP file containing the WordPress website for `wplib.box` from an `/opt/provision` directory inside the box to the box's `/var/www` directory _(which maps to `www/` in our host's directory)_ and then unzip it.

This will have the same effect as running `composer install` as if `composer install` was run at the time of box image creation instead of at time of first `vagrant up`.  That will give us a known working `wplib.box` website and on that website we can provide instructions for the user that would include one of:

1. Run `composer update` after running `vagrant ssh`, or
2. Run `composer update` on the host machine after ensuring that composer is installed.

**Comment by franz-josef-kaiser** [comment]
My 2cents after all the discussions we had:

This project is already at a point where it slightly defies the purpose of Vagrant: Provisioning. At the point where you start adding zipped packages and as there's already close to no provisioning going on, you can as well just provide a fully pre-provisioned VM. But that's like back in 2000 and obviously not this projects goal. 

Ad Composer and the ZIP: IIRC Composer can't switch resources, so you will have to either provide local packages that you can use, or you just drop Composer completely. There's no fallback from some remote location possible. Using Composer for a local install imho is somehow pointless.

The only reason to still use Vagrant now is the hostsupdater or a similar plugin. That could as well be replaced by a simple shell script to update the `vhosts` file.

Summed up, I personally think that the goal is set a bit too high and slowly but surely moves your project into a dead end and backwards instead of forwards. Still hope it helps that I have written my _opinion_ here for you.

**Comment by mikeschinkel** [comment]
> _My 2cents after all the discussions we had:_

Thanks for taking the effort.

> _This project is already at a point where it slightly defies the purpose of Vagrant: Provisioning._

That is actually not what I understand the point of Vagrant to be.  My understanding of the point of Vagrant was:

1. To provide a command line interface for VirtualBox (or VMware or Parallels)...
2. ...that loads an operating system and optionally provisioned image...
3. ...that mounts the host's project directory as the VM's web root directory...
4. ...that allows setting the IP address and local domain name...
5. ...that updates the host machine's `hosts` file...
6. ...and that _*optionally*_ runs a(n additional) provisioning script (Bash/Ansible/Puppet/Chef/etc.)

But rather than assume my understanding was right I decided to google a bit.  Here is what I found:

- On [Why Vagrant?](https://www.vagrantup.com/docs/why-vagrant/) _(**emphasis mine**)_ which seems to support my understanding that use of provisioning tools is *optional*:

> _Vagrant provides easy to configure, reproducible, and portable work environments built on top of industry-standard technology and controlled by a single consistent workflow to help maximize the productivity and flexibility of you and your team._
>
> _To achieve its magic, Vagrant stands on the shoulders of giants. Machines are provisioned on top of VirtualBox, VMware, AWS, or any other provider. Then, industry-standard provisioning tools such as shell scripts, Chef, or Puppet, **can be used** to automatically install and configure software on the machine._

Further I found the most up-voted answer to the question _"[What's the purpose of Vagrant?](https://www.reddit.com/r/rails/comments/1w7sid/whats_the_purpose_of_vagrant/)"_ on Hacker News _(with 37 votes)_ and none of the four points presented even mentions provisioning or implies that provisioning is a primary purpose of Vagrant:

<blockquote><em>
<ol><li>Because you want to provide a packaged development environment that's exactly the same across all of your developers. A new developer can just check out the code and run vagrant up and begin developing without needing to care about all of the resources used by your application (redis? postgresql? mysql? sphinx? solr?)
</li><li>Because you want to create a VM that closely resembles your production environment. For testing purposes, or pure developing, things work better the closer your development and production environments are (helps hammer out hard to find bugs in configuration/OS)
</li><li>Because your OPs team will benefit from it. Now that everyone's on the same page having a production-replica environment, your operations or deployment team (even if that's just you) can now test changing the infrastructure (your set of chef recipes, etc) and can test your deployment procedure.
</li><li>You can very easily spin up a new box with a different configuration of resources and test against it. Want to see what'll happen when upgrade your ruby version, your redis version, and your java version/solr version?
</ol></em></blockquote>

I even remember being told that Mitchel Hashimoto said that doing significant provisioning in a `Vagrantfile` was crazy and that a better approach was to use his Packer software to create an initial box that is pre-provisioned as much as possible.  And while I can't find a reference to his comment the fact his company offers [**Atlas**](https://atlas.hashicorp.com/boxes/search) and bills it as a place to _"Discover Vagrant Boxes"_ would tend to support the idea of pre-provisioning boxes to be used by Vagrant as much as possible.

So while I do absolutely respect your opinion and appreciate that you see Vagrant's primary value as its ability to support Provisioning I will also say that others -- including myself -- see provisioning within Vagrant as just being a necessary evil if you do not have a pre-provisioned box image.

> _Ad Composer and the ZIP_

You've used _"Ad"_ several times when communicating with me, but I do not know what it means. Does it mean "In Reference To?"

> _ IIRC Composer can't switch resources, so you will have to either provide local packages that you can use, or you just drop Composer completely. There's no fallback from some remote location possible. Using Composer for a local install imho is somehow pointless.

I must not have described what I meant so that you could understand, Let me try a different approach.

Let's assume we had Composer run as part of a provisioning process.  That would produce a directory of files that had been _"composed."_  Now assume that you conceptually ZIP and delete the directory, and then move the zip to `/opt/provision`. But in practice you are doing the same using Packer when building our base box image.

Then when `vagrant up` or `vagrant reload --provision` is run we have a tiny bash script that copies the ZIP file from `/opt/provision` to `/var/www` and unzips it.  Boom, we are done. Not need for switching resources, no local packages, no fallback to remote locations; just a ZIP file contain the results of `composer install`.

Now you may ask _"What if the ZIP file is out of date?"_  No problem, it will still work when someone new to WPLib Box clones the box for the first time -- which is one of our goals -- and all they will need to do to bring it up-to-date is run `composer update`; best of both worlds.

Maybe the best way to fully understand it is to see it in action after we get 0.10.6 out the door.

> _Summed up, I personally think that the goal is set a bit too high and slowly but surely moves your project into a dead end and backwards instead of forwards._

I do respect your opinion, and I thank you again for taking the time to verbalize it.  And you may be right.  But I have really clear vision about where we are headed with this and I see it as moving forwards significantly.  Maybe not for people as advanced as you, but for the 80% who are not.

And that will give us runway to be able to offer a much more powerful box later this year or maybe early next year after some of the needed software matures more.

**Comment by mikeschinkel** [comment]
@clubdeuce (and @franz-josef-kaiser):

After leaving that long reply above, another approach occurred to me that I had not previously considered.

Rather than use a ZIP file on the box image that would need to be updated every time any of the software contained within would need to be updated, why not run `composer update` on from a local copy of the repo at github.com/wplib/wplib-box that would include WordPress, plugins, theme, etc. and then instead of unzipping a zip file from the box itself change the provision process to simply add WordPress core and plugins and the `vendor` directory to `.gitignore`?

This would achieve the same goals I want to achieve because cloning the Git repo is something people will have to do and clone is typically super fast and I've never seen a clone fail as long as Git access has been set up to work correctly on the host/developer's machine.

@clubdeuce If you agree with this I can take this ticket and make the changes.

**Comment by clubdeuce** [comment]
@mike What is the status of this? Should we include in 0.10.7 or punt?

**Comment by mikeschinkel** [comment]
@clubdeuce Given I am heavily focused on WPLib `0.13.0` let's push this to `0.10.8`?

**Comment by mikeschinkel** [comment]
@clubdeuce I have basically resolved this.  We should discuss how I did it so that you are aware are you are adding features to the box.
