### ISSUE TITLE
MkDocs should not serve when called as just `mkdocs` [0.17.1]

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#481]
Currently you cannot run `mkdocs --version`; it starts serving instead.

MkDocs should not serve when called as just `mkdocs`.  Instead it should display list of available commands.

**Comment by MickMake** [comment]
"Ready for QA" test:
* `box component uninstall wplib/mkdocs:0.15.3` - remove existing component.
* `box component activate wplib/mkdocs:0.15.3` - activate updated component.
* Create index.html file or run `mkdocs build`.
* Test using http://docs.wplib.box/

**Comment by mikeschinkel** [comment]
![hmm](https://user-images.githubusercontent.com/153285/43483428-ab73a542-94d9-11e8-95e7-955520a57482.png)
![restart](https://user-images.githubusercontent.com/153285/43483530-f477011c-94d9-11e8-8b05-afd04e481691.png)

**Comment by MickMake** [comment]
"Ready for QA" test:
* `box self-update 0.17.1` - update box-scripts.
* `box component uninstall wplib/mkdocs:0.15.3` - remove existing component.
* `box component activate wplib/mkdocs:0.15.3` - activate updated component.
* Create index.html file or run mkdocs build.
* Test using http://docs.wplib.box/

**Comment by mikeschinkel** [comment]
Looks good.
