### ISSUE TITLE
How do I setup remote debugging with wplib-box?

### ISSUE THREAD

**Issue by taras** [wplib/wplib-box#50]
I'd like to use xDebug. Is there a good way to do this?

**Comment by clubdeuce** [comment]
@taras It is already setup.

![screen shot 2016-04-23 at 10 37 36 am](https://cloud.githubusercontent.com/assets/2600497/14762060/8a0d376a-093f-11e6-90df-d233b57de96d.png)
![screen shot 2016-04-23 at 10 37 55 am](https://cloud.githubusercontent.com/assets/2600497/14762061/8a0ee29a-093f-11e6-9a6b-1307a855dca1.png)

**Comment by taras** [comment]
Ok, I'll give it a try. Thanks :)

**Comment by clubdeuce** [comment]
My pleasure. Let me know if you have difficulties.

**Comment by taras** [comment]
Do I need to specify a different host?

**Comment by mikeschinkel** [comment]
@taras What specifically do you mean?
