### ISSUE TITLE
Provide instructions on how to configure Xdebug for Visual Studio Code

### ISSUE THREAD

**Issue by taras** [wplib/wplib-box#51]
I can get XDebug working with PHPStorm but not with Visual Studio Code. 

Might be worth looking into this cause Visual Studio Code is free.

**Comment by mikeschinkel** [comment]
Thanks @taras.  I'dd all this as a research item and see how soon we can figure it out.

**Comment by clubdeuce** [comment]
@taras I have investigated this and have Xdebug working with Visual Studio Code.

I will produce a set of instructions and let you know when I have posted it.

**Comment by taras** [comment]
awesome. Thank you

**Comment by clubdeuce** [comment]
@taras- Done. See https://github.com/wplib/wplib-box/blob/0.10.7.2/FAQ.md#vscode-debug
