### ISSUE TITLE
First time `box self-update` needs a better UX [0.17.1]

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#517]
![ux-git](https://user-images.githubusercontent.com/153285/43488294-3435e806-94e7-11e8-9d38-5dc554a876d2.png)

Clearly we need some way to get their username and password up-front so we can set.  Let's discuss.

**Comment by MickMake** [comment]
This was a bug that was fixed in #519 .

**Comment by mikeschinkel** [comment]
Seems to be fixed.
