### ISSUE TITLE
How to dump the database?

### ISSUE THREAD

**Issue by taras** [wplib/wplib-box#54]
I'm using `wplib-box` without MySQL installed locally. When I use `wp-cli db export` command, I get `sh: mysqldump: command not found`.

I suspect that installing mysql client won't help much cause the DB is inside of the VM.

What's the recommended way of dumping the DB with the current setup?

**Comment by clubdeuce** [comment]
@taras: wp-cli is installed in the virtual machine. You could export the database from there, or use a GUI muSQL client (Navicat, Sequel Pro, etc.) on the host.

**Comment by clubdeuce** [comment]
@taras the MySQL server will respond to requests on all interfaces, so installing MySQL client on your host will also work.

**Comment by taras** [comment]
@clubdeuce thank you

**Comment by mikeschinkel** [comment]
@clubdeuce Where is WP CLI installed?  When I `vagrant ssh` then type `wp` I get:

    wp: command not found

Is it installed but not in the path?

**Comment by clubdeuce** [comment]
@mikeschinkel It seems it is not installed, despite my adding it earlier. I have found the reason and will rectify.

**Comment by clubdeuce** [comment]
WP-CLI is now included in the box.
