### ISSUE TITLE
Explore storing MySQL Files on Shared Folder on the Host

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#55]
Per suggestion in Slack https://wplib.slack.com/archives/box/p1461747628000125 we should look at the potential to store the MySQL files in a Vagrant shared folder to see if performance is reasonable and to see if doing so results in corruption of files or not. 

To test the latter we'd need to try using it a while so we'd probably need a provision option to turn the feature on or off.

Discuss.

**Comment by sarutole** [comment]
This might be prohibitively slow on a Windows machine without NFS support.

**Comment by clubdeuce** [comment]
@mikeschinkel As Saru mentioned, I believe this would be *painfully* slow unless NFS support is enabled (which most Windows users will not have).

I suggest we close this issue as `will not implement`.

**Comment by mikeschinkel** [comment]
@clubdeuce 

> _I suggest we close this issue as will not implement._

The goal of the ticket was to come up with a way to store DB in a manner that would always persist the database so maybe the proposed solution won't work but maybe something else will.  Maybe the solution is a Docker container for the DB that runs on the host once we move to Docker?

So I added a `maybe-later` tag and removed you from it; we can just be on the lookout of viable solutions to address this later.
