### ISSUE TITLE
Adding rsync to synced_folder option generates error due to existing symlink

### ISSUE THREAD

**Issue by andreasnrb** [wplib/wplib-box#63]
Since I use symlink folders insidre the synced_folder I need to run rsync there. Doing that however results in an error due to the existing vagrant symlink to object-cache.php.
**option**
```
    config.vm.synced_folder "www", "/var/www", type: "rsync", rsync__args: ["--copy-links","--verbose", "--archive", "--delete", "-z"]
```
**error**
```
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: [...]/www/
Guest path: /var/www
Command: rsync --copy-links --verbose --archive --delete -z --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o ControlMaster=auto -o ControlPath=/tmp/ssh.387 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/home/andreas/.vagrant.d/insecure_private_key' --exclude .vagrant/ [...]/www/ vagrant@127.0.0.1:/var/www
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
symlink has no referent: "[...]/www/content/object-cache.php"
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

**Comment by mikeschinkel** [comment]
@andreasnrb This _**may**_ go away once we remove the need to `composer install` after cloning, but I am not sure since I don't yet know the use-case for `rsync

**Comment by andreasnrb** [comment]
It's so host symlinks in the synced folder gets correctly copied into the
client VM. Without it the symlinks are broken.

2016-04-29 19:53 GMT+02:00 Mike Schinkel <notifications@github.com>:

**Comment by andreasnrb** [comment]
Moving the symlink creation in provision.sh to in after-composer.php fixes the issue. Using synced_folder with rsync also automatically updates all symlinks in the folder so they match in the client VM.

**Comment by mikeschinkel** [comment]
@andreasnrb Cool.  So we can close the issue?

**Comment by andreasnrb** [comment]
The issue exist, that is just my local solution. Gonna test with NSF instead of rsync tomorrow and see if it solves the symlinks being wrong without having to change provision.sh.

**Comment by mikeschinkel** [comment]
Ok, but do you have suggestions on how we can change things to fix the issue you are having?

**Comment by andreasnrb** [comment]
Issue I had was solved by creating the object-cache.php symlink in after-composer.php instead of in provision.sh. Can't be default because then the symlink is not available in the VM. Other solution is to use [NFS](https://www.vagrantup.com/docs/synced-folders/nfs.html) for synced folder on *nix system. I wont be using rsync for my setup though since the fileupdates have to long delay. I suggest NFS or VM specific symlinks for people wanting to have symlinks on files they are writing in.
Closing this.
