### ISSUE TITLE
Suggestion: Standardize on Admin/Password

### ISSUE THREAD

**Issue by jimtrue** [wplib/wplib-box#64]
Will get those VVV folks flipping over faster if they don't have to remember to use a different login to get into your box.

**Comment by mikeschinkel** [comment]
@clubdeuce To clarify, the suggestion is to change the default login and password from `admin` / `admin` to instead `admin` / `password`.

Sounds like a good idea to me?

**Comment by clubdeuce** [comment]
Sure.

**Comment by mikeschinkel** [comment]
When this change is made we need to remember to update the [README.md section on credentials](https://github.com/wplib/wplib-box#logging-into-the-wordpress-admin).
