### ISSUE TITLE
Reduce size of Box Image 

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#65]
As a nice to have, it would be good to reduce the size of the box image.

[**Here is a link**](https://wiki.ubuntu.com/ReducingDiskFootprint) from Ubuntu that explains things that can be done to reduce size.

Another option to consider is to switch to a smaller distro, such as Arch Linux which Docker has chosen to enable them to create small images.
- https://www.digitalocean.com/community/tutorials/how-to-install-lemp-nginx-mysql-php-stack-on-arch-linux
- http://lifehacker.com/5680453/build-a-killer-customized-arch-linux-installation-and-learn-all-about-linux-in-the-process
- https://bbs.archlinux.org/viewtopic.php?id=96249

**Comment by clubdeuce** [comment]
This is an ever present concern. Closing this ticket.
