### ISSUE TITLE
Enable vagrant user to read root files or remove root password

### ISSUE THREAD

**Issue by andreasnrb** [wplib/wplib-box#69]
Cant read some files and folders as vagrant user such as php5-fpm.log.

**Comment by mikeschinkel** [comment]
Sounds reasonable.

**Comment by clubdeuce** [comment]
`sudo` will allow you to read the files.

**Comment by andreasnrb** [comment]
Weird when tried yesterday evening it didnt work properly. Today it did.
Bunch of stuff wroked today but not yesterday. oh well, I blame gremlins.

2016-05-02 2:49 GMT+02:00 Daryl Lozupone <notifications@github.com>:

**Comment by clubdeuce** [comment]
`sudo truncate logfile --size 0`
