### ISSUE TITLE
Not seeing WordPress site after fresh install

### ISSUE THREAD

**Issue by Obvio** [wplib/wplib-box#71]
Hi, thanks for this!
After updating to 0.10.6.2 and doing a fresh install everything (latest virtualbox and vagrant plugins) it looks like the server doesnt find the site, I get an NGINX welcome message and then all other urls like wplib.box/wp-admin all return 404.

here's a screenshot:

<img width="1177" alt="screen shot 2016-05-04 at 14 56 34" src="https://cloud.githubusercontent.com/assets/300232/15023946/1a95ddb0-1209-11e6-95f2-bc5f6ee9ba9f.png">

thanks!

**Comment by clubdeuce** [comment]
@Obvio have you done `composer install`?

**Comment by clubdeuce** [comment]
@Obvio Also, when you download a new box version, you will need to do a `vagrant destroy` and then a `vagrant up`.

**Comment by Obvio** [comment]
@clubdeuce thanks, yes I first destroyed and didn't forget composer install, I even tried it a couple of times in other folders but i get the same result. it looks like the wordpress files are in place but maybe where the server is pointing to is broken, not sure what to check for.

**Comment by clubdeuce** [comment]
@Obvio are you getting any errors from vagrant regarding the mounting of shared folders?

**Comment by Obvio** [comment]
no errors.. here's what i get when doing vagrant up

`Amits-MacBook-Pro:wplib-box Amit$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'wplib/wplib' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
GuestAdditions 5.0.20 running --- OK.
==> default: Checking for guest additions in VM...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> default: [vagrant-hostsupdater]   10.165.47.177  fn.dev  # VAGRANT: f73efc8ffa18e2902026143409cb2bd2 (default) / 4dd5ff7f-441c-4260-995b-0b6e8cfb806e
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/www => /Users/Amit/Projects/projectname/wplib-box/www
    default: /vagrant => /Users/Amit/Projects/projectname/wplib-box
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.`

**Comment by mikeschinkel** [comment]
@Obvio What time zone are you located in _(related to New York/EST?)_. Would you want to/be available to do a screenshare at 6pm EST or later today for me to diagnose?  Or tomorrow some time?

**Comment by mikeschinkel** [comment]
@Obvio Looking closer at your output, I see that you updated the `Vagrantfile` to use `fn.dev`, correct?  When you do that `wplib.box` no longer works, you should try `fn.dev` instead.

Does that help?

**Comment by Obvio** [comment]
@mikeschinkel yes, sorry, this was a second try i’ve made, same situation/error:
<img width="975" alt="screen shot 2016-05-04 at 22 57 55" src="https://cloud.githubusercontent.com/assets/300232/15034501/a3b165ae-124c-11e6-8727-7553107ab3b1.png">

i’ll ping you on the AWP FB group with my details and find out a time, this week at this time I won’t be around. thanks!

**Comment by mikeschinkel** [comment]
@Obvio One thing to check is to see if your `/etc/hosts` file _(for Mac & Linux, elsewhere for Windows)_ has `wplib.box` or `fn.dev` in it and if it is mapped to the correct IP address.  Your box has an IP address of `10.165.47.177` _(we generate and then store a random IP address starting with `10.` in the file named `IP` in the same folder as `Vagrantfile`.)_

If you have multiple conflicting entries in `/etc/hosts` that is likely the problem, or if you do not have any entries in `/etc/hosts` that would also be the problems _(but you would see an error if that were the case, I think.)_

If that does not solve it I would very much like to screen share with you at some time that is mutually convenient to diagnose the problem.

**Comment by clubdeuce** [comment]
@obvio Were you able to resolve this issue? Do you need further assistance from us?

**Comment by Obvio** [comment]
thanks for asking, i just tried it again with a fresh install and it works perfectly fine so we're ok! thanks again!

**Comment by clubdeuce** [comment]
@Obvio Very good.
