### ISSUE TITLE
Enable Git to be run via PHP

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#73]

**Comment by clubdeuce** [comment]
@mikeschinkel Git is already installed. Did you run into an issue trying to use it?

**Comment by mikeschinkel** [comment]
Yes, but in hindsight I might have been doing something wrong.  I'll check and report back.

**Comment by mikeschinkel** [comment]
@clubdeuce You are correct, **git** IS installed.   So I have renamed this issue.

What I want to be able to do if get PHP to trigger running Git.  I copied this code into `/var/www` as `test.php` and it outputs only `Array`:

    <?php
    echo "<pre>";
    exec( "git", $output );
    echo $output;
    echo "</pre>";

I did some googling and found these on the subject but was not able to get working on my machine. I am pretty sure I am missing something simple; can you figure it out?

- http://stackoverflow.com/questions/8562544/executing-git-commands-via-php
- http://stackoverflow.com/questions/23136044/automation-of-git-pull-using-php-code

**Comment by mikeschinkel** [comment]
@clubdeuce Nevermind, I am figuring it out.  Will post what works soon.

**Comment by mikeschinkel** [comment]
@clubdeuce So this worked:

    <?php
    echo "<pre>";
    echo shell_exec( "git init" );
    echo "</pre>";

Closing issue.
