### ISSUE TITLE
Add Node and Related tools

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#77]

**Comment by clubdeuce** [comment]
Also include `grunt-cli` and `gulp`

**Comment by mikeschinkel** [comment]
Add `npm` and `yeoman` too.

**Comment by clubdeuce** [comment]
@mikeschinkel Given the fact that we are moving towards a black box, this issue becomes a moot point. Once the user can no longer gain access via `ssh`, these tools will be useless.

**Comment by mikeschinkel** [comment]
@clubdeuce I have not been thinking we'd make it that much of a black box; I still think people need to be able to extend it -- by provisioning -- for their own uses, and especially providing then access to SSH. 

However, I think we should strive to give them every reason to not ever _need_ to extend it or access it via SSH.  A lot like OpenWRT.
