### ISSUE TITLE
Implement Internet Sharing

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#78]
Investigate options for Internet Sharing via localtunnel, ngrok, etc.

See Loopback Providers

- localtunnel.me
- ngrok.com
- forwardhq.com
- xip.io
- vagrantshare.com

**Comment by clubdeuce** [comment]
localtunnel.me is the simplest to implement, and has no associated cost to use it. Vagrant share is bundled with vagrant, so nothing to do there.

Let's implement localtunnel.me for 0.10.7 and look at the others as necessary in the future.
