### ISSUE TITLE
Implement PHP 5.6 + PHP 7.0

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#79]

**Comment by clubdeuce** [comment]
@mikeschinkel The answer for this has serendipitously fallen into my lap.

**Comment by clubdeuce** [comment]
@mikeschinkel I currently have both 5.6 and 7.0 versions of FPM running in the box simultaneously.

**Comment by mikeschinkel** [comment]
How does someone access/switch to them?

**Comment by clubdeuce** [comment]
@mikeschinkel you simply point the nginx site configuration to the desired from version socket.

**Comment by mikeschinkel** [comment]
More specifically?  How is it pointed exactly?   Does it require modification inside the box (I assume it does?)

**Comment by clubdeuce** [comment]
@mikeschinkel Yes. You set the `fast_cgi_pass parameter` inside the nginx configuration for the vhost.

**Comment by mikeschinkel** [comment]
@clubdeuce So this will be one of the first things we can set up a web API to run, and possibly to do so by interactive with Gearman?

**Comment by clubdeuce** [comment]
@mikeschinkel that sounds reasonable.
