### ISSUE TITLE
Fix issue where IP file not created on Windows

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#81]
Bash scripts do not run on Windows (doh!)  Needs to be Ruby for now.

**Comment by clubdeuce** [comment]
@mikeschinkel Status of this?

**Comment by mikeschinkel** [comment]
@clubdeuce A few days ago @andreasnrb mentioned `run_remote` for Vagrant and I think this will solve this issue, using it instead of `system`; does that sound workable?

**Comment by khromov** [comment]
@mikeschinkel Surely that can't work before the machine is booted though, so you can not use it for `config.vm.network`.

**Comment by mikeschinkel** [comment]
@khromov Ah yes.  Thanks.

**Comment by mikeschinkel** [comment]
This should be fixed now.
