### ISSUE TITLE
Error on reload/provision: Table 'wp_commentmeta' already exists

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#85]
The following occurs on `vagrant reload --provision`:
```
==> default: ERROR
==> default:  1050 (42S01)
==> default:  at line 29
==> default: : Table 'wp_commentmeta' already exists
```
We should probably throw a warning instead that explains that the database already exists and require a command line switch like `--force` or similar to overwrite the existing database.

**Comment by clubdeuce** [comment]
The data can be included in the box build process and eliminated from this repository altogether.

**Comment by mikeschinkel** [comment]
The error occurred after I copied a SQL file from another source and then re-provisioned to import into the box, but I see another ticket (#91) where you are disabling that capability? 

Maybe what we need is a process to replace the DB?  A script in the box to replace the DB, a task in Gearman to run the script, and API call to trigger the task, and an option in a console app to replace the DB?

**Comment by clubdeuce** [comment]
@Mikeschinkel we would also be alright if the sql to be imported includes `DROP TABLE IF EXISTS...`, yes?

**Comment by mikeschinkel** [comment]
@clubdeuce Well, yes. But when it does not include then we have this error thrown, which the user may not understand.  And there is the question of making sure the user to do drop data they did not realize what would happen.  So my suggestion basically makes these questions moot since I was also thinking about an automatic dump prior to import.

**Comment by clubdeuce** [comment]
@mikeschinkel That makes sense. So remove the database import from the provisioning, and add a process for importing the database.

Currently, users can import the database using an SQL client or the `mysql` cli in the box image itself.

**Comment by mikeschinkel** [comment]
@clubdeuce 
> _"So remove the database import from the provisioning, and add a process for importing the database."_

Agreed.

> _"Currently, users can import the database using an SQL client or the mysql cli in the box image itself."_

Yes. Need to add to FAQ: #93
