### ISSUE TITLE
vagrant up broken on Windows 10

### ISSUE THREAD

**Issue by khromov** [wplib/wplib-box#86]
The error points to:
https://github.com/wplib/wplib-box/blob/master/Vagrantfile#L263

Error log:
```
C:\Users\k\Documents\GitHub\wplib-box>vagrant up
C:/Users/k/Documents/GitHub/wplib-box/Vagrantfile:263:in `read': No such file or directory @ rb_sysopen - IP (Errno::ENOENT)
        from C:/Users/k/Documents/GitHub/wplib-box/Vagrantfile:263:in `block in <top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/loader.rb:37:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/loader.rb:37:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:113:in `block (2 levels) in load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:107:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:107:in `block in load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:104:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:104:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:28:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:740:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:740:in `vagrantfile'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:486:in `host'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:208:in `block in action_runner'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:33:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:33:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:473:in `hook'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:722:in `unload'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:177:in `ensure in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:177:in `<main>'
```

**Comment by mikeschinkel** [comment]
Hi @khromov:

Yes this is a known issue we plan to fix on `0.10.7`, to be available soon.   But the workaround is easy;  simply create a file name `IP` in the same folder as `Vagrantfile` and put the local IP address in it you want to use.   

Alternately change line `263` in `Vagrantfile` by replacing `IO.read('IP').strip` with your desired IP address, in quotes.

**Comment by clubdeuce** [comment]
@mikeschinkel What is the status of this?

**Comment by mikeschinkel** [comment]
I have been working on WPLib `0.13.0` recently, but we definitely need to tackle this.  I'll put on my to-do list for the holiday weekend.

**Comment by clubdeuce** [comment]
Result of #86

**Comment by andreasnrb** [comment]
@mikeschinkel why the need to generate IP at all? If box is provided as is just go with a default ip.

**Comment by mikeschinkel** [comment]
@andreasnrb So that when people use the box on multiple projects they do not conflict.

**Comment by andreasnrb** [comment]
They could just change IP in file or vagrant.

2016-06-02 4:28 GMT+02:00 Mike Schinkel <notifications@github.com>:

**Comment by mikeschinkel** [comment]
Yes, they absolutely could. But what will typically happen is that there will be an error, they will feel annoyed, and then they might google for the solution, figure out the issue and finally realize that they need to change the IP address.

As part of our mission for "Developer Experience" we want to attempt to make everything either "just work" on be completely discoverable so we currently think finding a random IP would be the best approach.  In the future we may be able to tell them the IP needs to be different, but again we want to do everything we can to ensure there as a few snags to the experience as possible.

**Comment by mikeschinkel** [comment]
This should be fixed now.
