### ISSUE TITLE
Can't create UNIX socket after running lots of requests

### ISSUE THREAD

**Issue by andreasnrb** [wplib/wplib-box#94]
Been running my acceptance test suite against the box quite a few times today and ended up getting the following error message.
`( ! ) Warning: mysqli_real_connect(): (HY000/2001): Can't create UNIX socket (24) in /var/www/wp/wp-includes/wp-db.php on line 1490`
Running `vagrant reload` resolved the issue. Not sure how to debug this. Havent cleared any logs.

**Comment by mikeschinkel** [comment]
@andreasnrb Hmm.  What are you using for acceptance testing?   Is it running on your host computer?  Does it hammer the HTTP server?

**Comment by andreasnrb** [comment]
Running a CasperJS testsuite. it doesn't do that much, visits pages and
fillls out forms. I'll see if and when it comes back.​

**Comment by mikeschinkel** [comment]
Are you running on your host, or in the guest?  If in the guest and you recreate it, maybe we could get the copy of the guest to allow us to debug it?

**Comment by andreasnrb** [comment]
Its running from the host. All it does is simulate a visitor logging in and
filling out forms. Visits maybe 10 pages. Fills out forms on 3 of them.
Will see if issue returns, havent encountered it again.

2016-06-02 7:01 GMT+02:00 Mike Schinkel <notifications@github.com>:

**Comment by mikeschinkel** [comment]
Okay, let us know.  If there is some what to help us simulate if for testing, such as getting your scripts and app that would help us find the problem quicker.

**Comment by clubdeuce** [comment]
@andreasnrb Are you still experiencing this issue?

**Comment by andreasnrb** [comment]
no i have not encountered it again. so could be closed. if it returns ill
let you know.

2016-06-15 19:39 GMT+02:00 Daryl Lozupone <notifications@github.com>:

**Comment by clubdeuce** [comment]
@andreasnrb Excellent.
